# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha512 = "S2Hw0TtNkMJhIabBwIojKL9YHO5T0n5eNqWJ7Lrlel/zDbftQpxpapi8tZs3X1HWa+u+QeydGmzzNU0m09+Rcg==";
      };
    };
    "clean-css-3.4.28" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "3.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-3.4.28.tgz";
        sha512 = "aTWyttSdI2mYi07kWqHi24NUU9YlELFKGOAgFzZjDN1064DMAOy2FBuoyGmkKRlXkbpXd0EVHmiVkbKhKoirTw==";
      };
    };
    "commander-2.8.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.8.1.tgz";
        sha512 = "+pJLBFVk+9ZZdlAOB5WuIElVPPth47hILFkmGym57aq8kwxsowvByvB0DHs1vQAhyMZzdcpTtF0VDKGkSDR4ZQ==";
      };
    };
    "copy-anything-2.0.6" = {
      name = "copy-anything";
      packageName = "copy-anything";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-anything/-/copy-anything-2.0.6.tgz";
        sha512 = "1j20GZTsvKNkc4BY3NpMOM8tt///wY3FpIzozTOFO2ffuZcV61nojHXVKIy3WM+7ADCy5FVhdZYHYDdgTU0yJw==";
      };
    };
    "debug-3.2.7" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.7.tgz";
        sha512 = "CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==";
      };
    };
    "errno-0.1.8" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.8.tgz";
        sha512 = "dJ6oBr5SQ1VSd9qkk7ByRgb/1SH4JZjCHSW/mr63/QcXO9zLVxvJ6Oy13nio03rxpSnVDDjFor75SjVeZWPW/A==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha512 = "8tLu60LgxF6XpdbK8OW3FA+IfTNBn1ZHGHKF4KQbEeSkajYw5PlYJcKluntgegDPTg8UkHjpet1T82vk6TQ68w==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha512 = "6TDAlDPZxUFCv+fuOkIoXT/V/f3Qbq8e37p+YOiYrUv3v9cc3/6x78VdfPgFVaB9dZYeLUfKgHRebpkm/oP2VQ==";
      };
    };
    "is-what-3.14.1" = {
      name = "is-what";
      packageName = "is-what";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-what/-/is-what-3.14.1.tgz";
        sha512 = "sNxgpk9793nzSs7bA6JQJGeIuRBQhAaNGG77kzYQgMkrID+lS6SlK07K5LaptscDlSaIgH+GPFzf+d75FVxozA==";
      };
    };
    "make-dir-2.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-2.1.0.tgz";
        sha512 = "LS9X+dc8KLxXCb8dni79fLIIUA5VyZoyjSMCwTluaXA0o27cCK0bhXkpgw+sTXVpPy/lSO57ilRixqk0vDmtRA==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "needle-3.1.0" = {
      name = "needle";
      packageName = "needle";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-3.1.0.tgz";
        sha512 = "gCE9weDhjVGCRqS8dwDR/D3GTAeyXLXuqp7I8EzH6DllZGXSUyxuqqLh+YX9rMAWaaTFyVAg6rHGL25dqvczKw==";
      };
    };
    "parse-node-version-1.0.1" = {
      name = "parse-node-version";
      packageName = "parse-node-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-node-version/-/parse-node-version-1.0.1.tgz";
        sha512 = "3YHlOa/JgH6Mnpr05jP9eDG254US9ek25LyIxZlDItp2iJtwyaXQb57lBYLdT3MowkUFYEV2XXNAYIPlESvJlA==";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "prr-1.0.1" = {
      name = "prr";
      packageName = "prr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-1.0.1.tgz";
        sha512 = "yPw4Sng1gWghHQWj0B3ZggWUm4qVbPwPFcRG8KyxiU7J2OHFSoEHKS+EZ3fv5l1t9CyCiop6l/ZYeWbrgoQejw==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha512 = "Y8nIfcb1s/7DcobUz1yOO1GSp7gyL+D9zLHDehT7iRESqGSxjJ448Sg7rvfgsRJCnKLdSl11uGf0s9X80cH0/A==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
  };
in
{
  "bootstrap-3.2.0" = nodeEnv.buildNodePackage {
    name = "bootstrap";
    packageName = "bootstrap";
    version = "3.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/bootstrap/-/bootstrap-3.2.0.tgz";
      sha512 = "MVUiqgpLinHRQlO8RIEsua7gmA+OHPD9wQU2ShAl+PzqmPXC0qzPgrynZEWTA6YlSY+APl7NEF3jXhBixadAvg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The most popular front-end framework for developing responsive, mobile first projects on the web.";
      homepage = "http://getbootstrap.com";
      license = {
        type = "MIT";
        url = "https://github.com/twbs/bootstrap/blob/master/LICENSE";
      };
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  less = nodeEnv.buildNodePackage {
    name = "less";
    packageName = "less";
    version = "4.1.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/less/-/less-4.1.3.tgz";
      sha512 = "w16Xk/Ta9Hhyei0Gpz9m7VS8F28nieJaL/VyShID7cYvP6IL5oHeL6p4TXSDJqZE/lNv0oJ2pGVjJsRkfwm5FA==";
    };
    dependencies = [
      sources."copy-anything-2.0.6"
      sources."debug-3.2.7"
      sources."errno-0.1.8"
      sources."graceful-fs-4.2.10"
      sources."iconv-lite-0.6.3"
      sources."image-size-0.5.5"
      sources."is-what-3.14.1"
      sources."make-dir-2.1.0"
      sources."mime-1.6.0"
      sources."ms-2.1.3"
      sources."needle-3.1.0"
      sources."parse-node-version-1.0.1"
      sources."pify-4.0.1"
      sources."prr-1.0.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."semver-5.7.1"
      sources."source-map-0.6.1"
      sources."tslib-2.4.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Leaner CSS";
      homepage = "http://lesscss.org";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  less-plugin-clean-css = nodeEnv.buildNodePackage {
    name = "less-plugin-clean-css";
    packageName = "less-plugin-clean-css";
    version = "1.5.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/less-plugin-clean-css/-/less-plugin-clean-css-1.5.1.tgz";
      sha512 = "Pc68AFHAEJO3aAoRvnUTW5iAiAv6y+TQsWLTTwVNqjiDno6xCvxz1AtfQl7Y0MZSpHPalFajM1EU4RB5UVINpw==";
    };
    dependencies = [
      sources."amdefine-1.0.1"
      sources."clean-css-3.4.28"
      sources."commander-2.8.1"
      sources."graceful-readlink-1.0.1"
      sources."source-map-0.4.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "clean-css plugin for less.js";
      homepage = "http://lesscss.org";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
