# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bootstrap-3.2.0" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-3.2.0.tgz";
        sha1 = "a0726e7c12e79f4a2a504f8d1ee9f2850a83f637";
      };
    };
    "less-2.7.1" = {
      name = "less";
      packageName = "less";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-2.7.1.tgz";
        sha1 = "6cbfea22b3b830304e9a5fb371d54fa480c9d7cf";
      };
    };
    "less-plugin-clean-css-1.5.1" = {
      name = "less-plugin-clean-css";
      packageName = "less-plugin-clean-css";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/less-plugin-clean-css/-/less-plugin-clean-css-1.5.1.tgz";
        sha1 = "cc57af7aa3398957e56decebe63cb60c23429703";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "graceful-fs-4.1.9" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.9.tgz";
        sha1 = "baacba37d19d11f9d146d3578bc99958c3787e29";
      };
    };
    "image-size-0.5.0" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.0.tgz";
        sha1 = "be7aed1c37b5ac3d9ba1d66a24b4c47ff8397651";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha1 = "75ce38f52bf0733c5a7f0c118d81334a2bb5f412";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "asap-2.0.5" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.5.tgz";
        sha1 = "522765b50c3510490e52d7dcfe085ef9ba96958f";
      };
    };
    "clean-css-3.4.20" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "3.4.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-3.4.20.tgz";
        sha1 = "c0d8963b5448e030f0bcd3ddd0dac4dfe3dea501";
      };
    };
    "commander-2.8.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.8.1.tgz";
        sha1 = "06be367febfda0c330aa1e2a072d3dc9762425d4";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha1 = "eba4f5da9c0dc999de68032d8b4f76173652036b";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "amdefine-1.0.0" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz";
        sha1 = "fd17474700cb5cc9c2b709f0be9d23ce3c198c33";
      };
    };
  };
  args = {
    name = "passe-deps";
    packageName = "passe-deps";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."bootstrap-3.2.0"
      sources."less-2.7.1"
      sources."less-plugin-clean-css-1.5.1"
      sources."errno-0.1.4"
      sources."graceful-fs-4.1.9"
      sources."image-size-0.5.0"
      sources."mime-1.3.4"
      sources."mkdirp-0.5.1"
      sources."promise-7.1.1"
      sources."source-map-0.5.6"
      sources."prr-0.0.0"
      sources."minimist-0.0.8"
      sources."asap-2.0.5"
      (sources."clean-css-3.4.20" // {
        dependencies = [
          sources."source-map-0.4.4"
        ];
      })
      sources."commander-2.8.1"
      sources."graceful-readlink-1.0.1"
      sources."amdefine-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}