### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "2c9566f0b0de5ab6dad7ce8d22b68a2999a1861f";
          sha256 = "0n6kk1z6bwfcsc0jzqjvxszbqq56xfnj47w91p9dd8s6gnayagyv";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.12.1";
  selection = 
  {
    angstrom = 
    {
      pname = "angstrom";
      version = "0.16.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/angstrom/archive/0.16.1.tar.gz";
        sha256 = "02qhk8s6hgr9i14d5qclvp9qw1syc500i6dr772p95849pxkcd8l";
      };
      opamInputs = 
      {
        inherit (selection) ocaml-syntax-shims ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/angstrom/angstrom.0.16.1";
        hash = "sha256:10dvrkw29pv310858qnvpn49hzr5f3bihzvm30yak7wp96xlpd7d";
      };
    };
    arp = 
    {
      pname = "arp";
      version = "3.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/arp/releases/download/v3.1.1/arp-3.1.1.tbz";
        sha256 = "1w86iy3ccs1sbdl01rj09zmgxzbwal5vmhibnq7k1snyx64wacza";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-time macaddr lwt logs ipaddr fmt
        ethernet duration dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/arp/arp.3.1.1";
        hash = "sha256:12drri632893xzl2ikz16iis41c206bhbq95y7shs6myydcqf7k8";
      };
    };
    asn1-combinators = 
    {
      pname = "asn1-combinators";
      version = "0.2.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.2.6/asn1-combinators-v0.2.6.tbz";
        sha256 = "148s3clqws2nmzwhvlgy0b3nnvq2xbw1qb3mcc865vv9i06xwah1";
      };
      opamInputs = 
      {
        inherit (selection) zarith ptime ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/asn1-combinators/asn1-combinators.0.2.6";
        hash = "sha256:03s1aska9ws9pnjm3v7f69qcx5gdmjh53ximh5zy9v9vf2sxbdsr";
      };
    };
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1s55pjjirhx1ra24nh5ckc3xnc2is64w08kz5bdc9cykff845k88";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "050syrp6v00gn50d6xvwv6a36zsk4zmahymgllxpw9paf4qk0pkm";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.15.1";
        hash = "sha256:0gx21y0rnza0dqj3i1fdblf9n3cd56awyd9md3dd8v41f1fvqi97";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base64 = 
    {
      pname = "base64";
      version = "3.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz";
        sha256 = "1vb53ijh098d8x0d5a2c7x9ar2j7vll5k2y0mkkylbyikfjxmznq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base64/base64.3.5.1";
        hash = "sha256:0qw6lbd3fjpdll98ihhwzry3xdd2syr545rnbb8fxffzwkpn7nwa";
      };
    };
    bigstringaf = 
    {
      pname = "bigstringaf";
      version = "0.10.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.10.0.tar.gz";
        sha256 = "0a4zfb1plzvcq42rfkxfm4bkg3q6n5clswzczkgbj4dwbyqgb4pd";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigstringaf/bigstringaf.0.10.0";
        hash = "sha256:12d9a9sh5zl0wngxb66kg7gd9j2q40hkwakl7wsh5v22gl1hcrhl";
      };
    };
    bos = 
    {
      pname = "bos";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/bos/releases/bos-0.2.1.tbz";
        sha256 = "0dwg7lpaq30rvwc5z1gij36fn9xavvpah1bj8ph9gmhhddw2xmnq";
      };
      opamInputs = 
      {
        inherit (selection) topkg rresult ocamlfind ocamlbuild ocaml logs
        fpath fmt base-unix astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bos/bos.0.2.1";
        hash = "sha256:0gzad9hndy8iz2pi9kjpfvpd85a0spplr5l2ci14z7z6cbnsnc9f";
      };
    };
    ca-certs = 
    {
      pname = "ca-certs";
      version = "0.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ca-certs/releases/download/v0.2.3/ca-certs-0.2.3.tbz";
        sha256 = "170fqqprqg6nxmc4y8905vwmcbzcwlxjzy6yhgbzcpligm2xdn6j";
      };
      opamInputs = 
      {
        inherit (selection) x509 ptime ocaml mirage-crypto logs fpath dune
        bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ca-certs/ca-certs.0.2.3";
        hash = "sha256:0d0nlgfqg94if6wn0nm3a92jnqa6k4ybajphb08lj4ikz7k3q5fy";
      };
      buildInputs = [ (pkgs.ca_root_nss or null) ];
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:0ajfln6isk2vlmvdmrib8xpxpv19634lkv6ppj8gjf0y7vhibjpx";
      };
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/cmdliner/releases/cmdliner-1.3.0.tbz";
        sha256 = "1fwc2rj6xfyihhkx4cn7zs227a74rardl262m2kzch5lfgsq10cf";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.3.0";
        hash = "sha256:0zw4amnvby9mi3r8kzknwfcrkf56lr2xmd7n3y47374jw17b3xpr";
      };
    };
    cohttp = 
    {
      pname = "cohttp";
      version = "6.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0/cohttp-6.0.0.tbz";
        sha256 = "1a92xzqmw6isx56hw983spyiyrk61mjnk9h8wr52yd4b2apk9k2l";
      };
      opamInputs = 
      {
        inherit (selection) uri-sexp uri stringext sexplib0 re ppx_sexp_conv
        ocaml logs http dune base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp/cohttp.6.0.0";
        hash = "sha256:1ssnij7aqbim4488hrwq5b5daxbnv3qb8p526bmhrr3iwdirqzgw";
      };
    };
    cohttp-lwt = 
    {
      pname = "cohttp-lwt";
      version = "6.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0/cohttp-6.0.0.tbz";
        sha256 = "1a92xzqmw6isx56hw983spyiyrk61mjnk9h8wr52yd4b2apk9k2l";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv ocaml lwt logs http
        dune cohttp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt/cohttp-lwt.6.0.0";
        hash = "sha256:0a0469464p1s2d3ii5r6knbr30461szmhh2457d0dhqk2hw43kp8";
      };
    };
    cohttp-lwt-unix = 
    {
      pname = "cohttp-lwt-unix";
      version = "6.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0/cohttp-6.0.0.tbz";
        sha256 = "1a92xzqmw6isx56hw983spyiyrk61mjnk9h8wr52yd4b2apk9k2l";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_conv ocaml magic-mime lwt logs http fmt
        dune conduit-lwt-unix conduit-lwt cohttp-lwt cohttp cmdliner
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0";
        hash = "sha256:11sxlq757d1z7zg1www3p9iymrdnf3hw2nj8449i94hgqfpgpf5m";
      };
    };
    conduit = 
    {
      pname = "conduit";
      version = "6.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.3/conduit-6.2.3.tbz";
        sha256 = "0y9y89jafndxr8spnindqa97w0p1asix0k88sr3z5cc52jxq8iis";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib ppx_sexp_conv ocaml logs ipaddr-sexp
        ipaddr dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit/conduit.6.2.3";
        hash = "sha256:1qyffihwl4dg4kc044g20lfrs7c5gl0qkhdim2xil0r7zf85gk6b";
      };
    };
    conduit-lwt = 
    {
      pname = "conduit-lwt";
      version = "6.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.3/conduit-6.2.3.tbz";
        sha256 = "0y9y89jafndxr8spnindqa97w0p1asix0k88sr3z5cc52jxq8iis";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ppx_sexp_conv ocaml lwt dune conduit
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt/conduit-lwt.6.2.3";
        hash = "sha256:0q1s8zwhvwxf68lr4kxz6b9ykls5pzg2fdkysxzj57izb04wg9nc";
      };
    };
    conduit-lwt-unix = 
    {
      pname = "conduit-lwt-unix";
      version = "6.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.3/conduit-6.2.3.tbz";
        sha256 = "0y9y89jafndxr8spnindqa97w0p1asix0k88sr3z5cc52jxq8iis";
      };
      opamInputs = 
      {
        inherit (selection) uri ppx_sexp_conv ocaml lwt logs ipaddr-sexp
        ipaddr dune conduit-lwt ca-certs
        base-unix;
        tls-lwt = selection.tls-lwt or null;
        lwt_ssl = selection.lwt_ssl or null;
        launchd = selection.launchd or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt-unix/conduit-lwt-unix.6.2.3";
        hash = "sha256:0v2p52k1n8pc140b0ag7hz9sanhpsjgdiyd2250v1cr0vbjw0vvn";
      };
    };
    conf-git = 
    {
      pname = "conf-git";
      version = "1.1";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-git/conf-git.1.1";
        hash = "sha256:1wcy3mzgsjg7xn9pb5p28ipi0av3nbmcv55fcpxxzvmpj9g96ykl";
      };
      buildInputs = [ (pkgs.git) ];
    };
    conf-gmp = 
    {
      pname = "conf-gmp";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp/conf-gmp.4";
        hash = "sha256:0fdi3yqm20sj19kfw6x1wjgvi0mhdbxbvh7jixk57fj5rg6xpi81";
      };
      buildInputs = [ (pkgs.gmp) ];
      extraSources = [ 
                        {
                          dest = "test.c";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-gmp/test.c.4";
                            sha256 = "1yynqhygxk4qckynwm61ggfr0i3gf5spwx162m9s4wgjy4shg8sl";
                          };
                        } ];
    };
    conf-gmp-powm-sec = 
    {
      pname = "conf-gmp-powm-sec";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.3";
        hash = "sha256:1vji17kz5lya9fc893fj49jx6ks9fdlvbb3ac1h81h4r0y9g39c1";
      };
      extraSources = [ 
                        {
                          dest = "test.c";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-gmp-powm-sec/test.c.3";
                            sha256 = "146lva7p06a4lp9v83p462zffbd5wa720s4vwpkafmq2adwki2rq";
                          };
                        } ];
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.4";
        hash = "sha256:1jkfhk77kwgqrignvdjajpc3kps7sbw6mj8gmi0wmjv18ziwhmis";
      };
      buildInputs = [ (pkgs.pkg-config) ];
    };
    conf-python-3 = 
    {
      pname = "conf-python-3";
      version = "9.0.0";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-python-3/conf-python-3.9.0.0";
        hash = "sha256:1jbiz9vrdz42i9dk454mvqrwk1pdfqw6d3cn1g7h4mhvkjcxvg1n";
      };
      buildInputs = [ (pkgs.python3) ];
      extraSources = [ 
                        {
                          dest = "test.py";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-python-3/test.py";
                            sha256 = "0xvv3fxp8v33j6h20rfzfw58yxhyyb3q7839xij69gs7yxcqnwsh";
                          };
                        } ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.8.0.tar.gz";
        sha256 = "03y0pbl1yhz1k39560s2bk08k3gb33mi00c6slwcrj8p0bpahqkf";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.8.0";
        hash = "sha256:0ga0qki08lxciw4kf3afqzyj0535afi9c50b6x4aap1whajsj20z";
      };
    };
    crunch = 
    {
      pname = "crunch";
      version = "3.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-crunch/releases/download/v3.3.1/crunch-3.3.1.tbz";
        sha256 = "0spdm3znj6r705sd86lcz31qfx2aqjvaykms3irvgjqb27aa0nrc";
      };
      opamInputs = 
      {
        inherit (selection) ptime ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/crunch/crunch.3.3.1";
        hash = "sha256:04zkajphh0yybhpcp7sw16h0wpmmgjx3gbs7rwq70il6hsj7p6aw";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    cstruct = 
    {
      pname = "cstruct";
      version = "6.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.2.0/cstruct-6.2.0.tbz";
        sha256 = "0qiyy1h7qsy90hdl01qdsg4rv61f3d5sp8wg2i4q63jqj8rhfy4s";
      };
      opamInputs = {
                     inherit (selection) ocaml fmt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct/cstruct.6.2.0";
        hash = "sha256:0r6dag0mhrs61gyh6pcf888s5npmgwj9rxag1d6a700p866cza7q";
      };
    };
    cstruct-lwt = 
    {
      pname = "cstruct-lwt";
      version = "6.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.2.0/cstruct-6.2.0.tbz";
        sha256 = "0qiyy1h7qsy90hdl01qdsg4rv61f3d5sp8wg2i4q63jqj8rhfy4s";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt dune cstruct base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct-lwt/cstruct-lwt.6.2.0";
        hash = "sha256:14cq0dnnz3bsw00m559501wyfgy7fsj0qyb1mlv304wmhj1j2c1v";
      };
    };
    dns = 
    {
      pname = "dns";
      version = "8.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v8.0.0/dns-8.0.0.tbz";
        sha256 = "0kl5v0kwkc4l4yay52iz3f9wafijca0cm13cn9d539xzqldhd0h8";
      };
      opamInputs = 
      {
        inherit (selection) ptime ocaml metrics lru logs ipaddr gmap fmt
        duration dune domain-name cstruct base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns/dns.8.0.0";
        hash = "sha256:1jikv6yb9qiacg709bsj0f4m5ncy9mm580jmkrsin42099cszh69";
      };
    };
    dns-client = 
    {
      pname = "dns-client";
      version = "8.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v8.0.0/dns-8.0.0.tbz";
        sha256 = "0kl5v0kwkc4l4yay52iz3f9wafijca0cm13cn9d539xzqldhd0h8";
      };
      opamInputs = 
      {
        inherit (selection) randomconv ocaml mtime mirage-crypto-rng ipaddr
        fmt dune domain-name dns;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns-client/dns-client.8.0.0";
        hash = "sha256:136v2h6v57n19z47qc2zp7lbml4swjmdvw166k98g87wdf0kqg0g";
      };
    };
    dns-client-lwt = 
    {
      pname = "dns-client-lwt";
      version = "8.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v8.0.0/dns-8.0.0.tbz";
        sha256 = "0kl5v0kwkc4l4yay52iz3f9wafijca0cm13cn9d539xzqldhd0h8";
      };
      opamInputs = 
      {
        inherit (selection) tls-lwt ocaml mtime mirage-crypto-rng-lwt lwt
        ipaddr happy-eyeballs-lwt happy-eyeballs dune dns-client dns
        ca-certs;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns-client-lwt/dns-client-lwt.8.0.0";
        hash = "sha256:15d96gk5153xw9l4rs47ql7a9swz1xmq1bivxpbjmxkj9m9ih2zp";
      };
    };
    domain-name = 
    {
      pname = "domain-name";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/domain-name/releases/download/v0.4.0/domain-name-0.4.0.tbz";
        sha256 = "1i8846nw81w0dkd76y0a3jw1sk9734qgw4p8fccj15aqhhi6xh55";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/domain-name/domain-name.0.4.0";
        hash = "sha256:12pk99v7dvmd1cc8v04pg8pxs5a3djwnc6mr056j9k5c7m8zazs9";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.17.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.17.2/dune-3.17.2.tbz";
        sha256 = "0r7al83jwkdfk6qvb53vrlzzfr08gwcydn1ccigfdsfg1vnzxslx";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.17.2";
        hash = "sha256:1535cmis823rj9gwacc9x4izsw25nd23fq32mnqgbcm3kphzys27";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.17.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.17.2/dune-3.17.2.tbz";
        sha256 = "0r7al83jwkdfk6qvb53vrlzzfr08gwcydn1ccigfdsfg1vnzxslx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.17.2";
        hash = "sha256:0b9zcvp1l5kkbqmdvjaahl1g2082c64bbvbw88nkp32q3d8dbkls";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.17.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.17.2/dune-3.17.2.tbz";
        sha256 = "0r7al83jwkdfk6qvb53vrlzzfr08gwcydn1ccigfdsfg1vnzxslx";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.17.2";
        hash = "sha256:0870n7labsblq34ph4szk8pmm3qd63f55mm6cpcx48pqdqkfwqxk";
      };
    };
    duration = 
    {
      pname = "duration";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/duration/releases/download/v0.2.1/duration-0.2.1.tbz";
        sha256 = "0aqyqzkrkkn33jysq3nmy0l24jyy37wdvlqw286856gvikrw2f67";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/duration/duration.0.2.1";
        hash = "sha256:0mw3xbzjfxlqhz479wgncjk2xf9fsbyxw516mk2f2i0yin14gxb2";
      };
    };
    emile = 
    {
      pname = "emile";
      version = "1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/emile/releases/download/v1.1/emile-v1.1.tbz";
        sha256 = "0r1141makr0b900aby1gn0fccjv1qcqgyxib3bzq8fxmjqwjan8p";
      };
      opamInputs = 
      {
        inherit (selection) uutf pecu ocaml ipaddr dune bigstringaf base64
        angstrom;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/emile/emile.1.1";
        hash = "sha256:1ncaci71knizw15p79gfy1g9vqpm2lk352k59s90hb47kyyv4ykn";
      };
    };
    eqaf = 
    {
      pname = "eqaf";
      version = "0.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/eqaf/releases/download/v0.9/eqaf-0.9.tbz";
        sha256 = "1q6zanrbj0ddrxwhwqdv1223mbk1k5dg0m2qbpwifs5c8sljh3pc";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/eqaf/eqaf.0.9";
        hash = "sha256:12yfvhy9n7qmfy8z6ppz15s13n9l3n0pqpyqms5kalqwcfnxaf7i";
      };
    };
    ethernet = 
    {
      pname = "ethernet";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ethernet/releases/download/v3.2.0/ethernet-3.2.0.tbz";
        sha256 = "02dcf88f4z8rvwjxbj3ngwscmldk7lpdxzx9jd1rs7922h1af7ac";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-net macaddr lwt logs dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ethernet/ethernet.3.2.0";
        hash = "sha256:04ai22mmbsa9z5ly2yi9lkwa9lzrdmc754j6sg1qid5qcqfkqiwl";
      };
    };
    extlib = 
    {
      pname = "extlib";
      version = "1.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ygrek/ocaml-extlib/releases/download/1.8.0/extlib-1.8.0.tar.gz";
        sha256 = "0w2xskv8hl0fwjri68q5bpf6n36ab4fp1q08zkfqw2i807q7fhln";
      };
      opamInputs = {
                     inherit (selection) ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/extlib/extlib.1.8.0";
        hash = "sha256:1jqy1g69akcdn5jc9gvkgqsnfgxsirg2pj1xzynbw2q9p67i0inx";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
        sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.9.0";
        hash = "sha256:0l58q3f7cp7xq6kqpm1gczg6s2v5v34jc5z4g2ss31q5i13yvdx3";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:0l4g37bj1jcy7z5dsi27vmmq40j749wy0i8z7v96mpdvsr26216k";
      };
    };
    gmap = 
    {
      pname = "gmap";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz";
        sha256 = "073wa0lrb0jj706j87cwzf1a8d1ff14100mnrjs8z3xc4ri9xp84";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/gmap/gmap.0.3.0";
        hash = "sha256:1k4f9vy0kxk7wdfakjxd826l0l59hcza247mga6xrkyrn3zcazin";
      };
    };
    happy-eyeballs = 
    {
      pname = "happy-eyeballs";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/robur-coop/happy-eyeballs/releases/download/v1.2.2/happy-eyeballs-1.2.2.tbz";
        sha256 = "1brfclji1gamana57n8mnvpbj89zgjm7x7d866qbkhhc0ikh4p8a";
      };
      opamInputs = 
      {
        inherit (selection) ocaml logs ipaddr fmt duration dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/happy-eyeballs/happy-eyeballs.1.2.2";
        hash = "sha256:0n0kkgmb27fba8iiwh2cm6m99sd2qrv6smpqma0hf6vbm0jps8lz";
      };
    };
    happy-eyeballs-lwt = 
    {
      pname = "happy-eyeballs-lwt";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/robur-coop/happy-eyeballs/releases/download/v1.2.2/happy-eyeballs-1.2.2.tbz";
        sha256 = "1brfclji1gamana57n8mnvpbj89zgjm7x7d866qbkhhc0ikh4p8a";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mtime lwt logs ipaddr happy-eyeballs fmt
        duration dune domain-name dns cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/happy-eyeballs-lwt/happy-eyeballs-lwt.1.2.2";
        hash = "sha256:06khml7b4b497gah0qgrksx059j6nshamap1gfjq863jkzhxnrvc";
      };
    };
    hex = 
    {
      pname = "hex";
      version = "1.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-hex/releases/download/v1.5.0/hex-1.5.0.tbz";
        sha256 = "1p5la5rn9nzvjyslysragwz2vjsbd76vac88lc3r61033g5fwrrf";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hex/hex.1.5.0";
        hash = "sha256:0d3sa6fls4yycsjsdf52lzhg7yav3j7ji7p0smm57799gwgfc6a8";
      };
    };
    hkdf = 
    {
      pname = "hkdf";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/ocaml-hkdf/releases/download/v1.0.4/hkdf-v1.0.4.tbz";
        sha256 = "0nzx6vzbc1hh6vx1ly8df4b16lgps6zjpp9mjycsnnn49bddc9mr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hkdf/hkdf.1.0.4";
        hash = "sha256:128gdp2v3qdg11rr6q4xbg0c2rv6yfv3rw20y6kkhbr2rp5z7hxx";
      };
    };
    http = 
    {
      pname = "http";
      version = "6.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0/cohttp-6.0.0.tbz";
        sha256 = "1a92xzqmw6isx56hw983spyiyrk61mjnk9h8wr52yd4b2apk9k2l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/http/http.6.0.0";
        hash = "sha256:0rq6s105d4fqh5zwcwg7vb841nl3jxxqba3ifz0cifkv00wyjmns";
      };
    };
    ipaddr = 
    {
      pname = "ipaddr";
      version = "5.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz";
        sha256 = "0cw1431idd54v067p3mqbxhsgsx5mixl9ywgmak3g92cvczl6c4y";
      };
      opamInputs = 
      {
        inherit (selection) ocaml macaddr dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr/ipaddr.5.6.0";
        hash = "sha256:07ppnhkbx05zz9ydrfyv65263505h3rh3d2c0irsjssbra59kimc";
      };
    };
    ipaddr-cstruct = 
    {
      pname = "ipaddr-cstruct";
      version = "5.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz";
        sha256 = "0cw1431idd54v067p3mqbxhsgsx5mixl9ywgmak3g92cvczl6c4y";
      };
      opamInputs = 
      {
        inherit (selection) ocaml ipaddr dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr-cstruct/ipaddr-cstruct.5.6.0";
        hash = "sha256:041327ymmkxfvq9dg32ngi5r49378qqcyrhzqk4367ja6njs9rmq";
      };
    };
    ipaddr-sexp = 
    {
      pname = "ipaddr-sexp";
      version = "5.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz";
        sha256 = "0cw1431idd54v067p3mqbxhsgsx5mixl9ywgmak3g92cvczl6c4y";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppx_sexp_conv ocaml ipaddr dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr-sexp/ipaddr-sexp.5.6.0";
        hash = "sha256:0yylzx7spgk5bh3zc269b6cl4z39mby7k6m21z8kx3cqg6rga591";
      };
    };
    js_of_ocaml = 
    {
      pname = "js_of_ocaml";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) uchar ppxlib ocaml js_of_ocaml-compiler dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml/js_of_ocaml.3.9.0";
        hash = "sha256:1q0z0p1knw78yia0wg1svhr767xk5hx3ygffzh3nx254ql7mlqsa";
      };
    };
    js_of_ocaml-compiler = 
    {
      pname = "js_of_ocaml-compiler";
      version = "3.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.1/js_of_ocaml-3.9.1.tbz";
        sha256 = "0ib551kfsjlp9vr3fk36hrbq7xxyl8bj6vcn3ccr0s370bsmgpm6";
      };
      opamInputs = 
      {
        inherit (selection) yojson ppxlib ocaml menhir dune
        cmdliner;
        ocamlfind = selection.ocamlfind or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.9.1";
        hash = "sha256:0s6r62yk169wm208ssnx5d0ljpj1bqrlcqsbg3bx8fqjx2n0840f";
      };
    };
    js_of_ocaml-lwt = 
    {
      pname = "js_of_ocaml-lwt";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt js_of_ocaml-ppx js_of_ocaml
        dune;
        lwt_log = selection.lwt_log or null;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-lwt/js_of_ocaml-lwt.3.9.0";
        hash = "sha256:0cyfqakgmkg3xgmgymvgkm8wx04m2azjkj7r3lza2s3rjaaymk5x";
      };
    };
    js_of_ocaml-ppx = 
    {
      pname = "js_of_ocaml-ppx";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml js_of_ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-ppx/js_of_ocaml-ppx.3.9.0";
        hash = "sha256:0dxypkk5gk6f0kh2mf21qqcmzxzb68albcpb1mpvp4pjivfsij60";
      };
    };
    jsonm = 
    {
      pname = "jsonm";
      version = "1.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/jsonm/releases/jsonm-1.0.2.tbz";
        sha256 = "1mkvi88vwn4rxa5ir3k5qhm8h8z15iyd5rp1ycfj0ls0xfgj6aga";
      };
      opamInputs = 
      {
        inherit (selection) uutf topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jsonm/jsonm.1.0.2";
        hash = "sha256:0agvb0jyq0wkkw7i4p24hgfwcmh0iy3fcfwlc9818sd9q0v5pi1r";
      };
    };
    lambda-term = 
    {
      pname = "lambda-term";
      version = "3.3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/lambda-term/archive/refs/tags/3.3.2.tar.gz";
        sha256 = "0jamxgzjy74j2b8jrs1jgrn6vm63nnvzir7hj9hwaynv4dnzai1d";
      };
      opamInputs = 
      {
        inherit (selection) zed react ocaml mew_vi lwt_react lwt logs dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambda-term/lambda-term.3.3.2";
        hash = "sha256:13w19dgjfp148bc857snrvy5pnvd2czwv1jh89dxry52ddswl5xp";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:12x7si2lmqzlb505wyk10lqczmjrhszjlr5bd6h3ycx4kdnkh5md";
      };
    };
    lru = 
    {
      pname = "lru";
      version = "0.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/pqwy/lru/releases/download/v0.3.1/lru-0.3.1.tbz";
        sha256 = "1z9nnba2b4q0q0syyqk4790hzxs71la8h2wwhr7j8nvxgb927gkc";
      };
      opamInputs = {
                     inherit (selection) psq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lru/lru.0.3.1";
        hash = "sha256:0g1gp7p8hzw84cdnmwdyvc2bcpjg06sb86fmmmq2sc6qkxs7hnif";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.9.0.tar.gz";
        sha256 = "1p9fc6kkjb0dh1c1lrvf929l342hpmkr0rp66kfxb4scwzs10ws2";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.9.0";
        hash = "sha256:0p1vj8rsbnzq2p7k07gd8h775y2a452kc8ha3bvascb4kqlgsgbn";
      };
    };
    lwt-dllist = 
    {
      pname = "lwt-dllist";
      version = "1.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/lwt-dllist/releases/download/v1.0.1/lwt-dllist-v1.0.1.tbz";
        sha256 = "0vms1py6qh0k8vi6n4wnmrfwpi44a4gfgcpq9i8m23gh81gffv78";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt-dllist/lwt-dllist.1.0.1";
        hash = "sha256:0ygfjbnsmjq78qg26iq1vkhgcmj5gg4mi2nhalcgbz8imm1wlhpf";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "5.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.8.0.tar.gz";
        sha256 = "17dzjiy1smv2791399j6gn2jxa4mkps2vrss231pp9m10lxfkdyi";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.5.8.0";
        hash = "sha256:0syifnrsq0xn7alv46jp7imm9bvsrzxn9fgxr875vw9v8q4ivyfv";
      };
    };
    lwt_react = 
    {
      pname = "lwt_react";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml lwt dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_react/lwt_react.1.2.0";
        hash = "sha256:0nar357nms1b90rr0iy2pa0m982yibwkbnx71hsz2v16kj9n831g";
      };
    };
    macaddr = 
    {
      pname = "macaddr";
      version = "5.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz";
        sha256 = "0cw1431idd54v067p3mqbxhsgsx5mixl9ywgmak3g92cvczl6c4y";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr/macaddr.5.6.0";
        hash = "sha256:1b88c3k02arrliic9jg75xczaffxcdd417qvwfzmhwn69z1hgj5v";
      };
    };
    macaddr-cstruct = 
    {
      pname = "macaddr-cstruct";
      version = "5.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz";
        sha256 = "0cw1431idd54v067p3mqbxhsgsx5mixl9ywgmak3g92cvczl6c4y";
      };
      opamInputs = 
      {
        inherit (selection) ocaml macaddr dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr-cstruct/macaddr-cstruct.5.6.0";
        hash = "sha256:0x3p92falrjd4dry3d4y57s6kpg2n0p339s91n2j8jq9fzscp9sa";
      };
    };
    magic-mime = 
    {
      pname = "magic-mime";
      version = "1.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.3.1/magic-mime-1.3.1.tbz";
        sha256 = "021vy409qq0gzsn4kzr1lvlsax9dcy3y6mwfqpx1xfjxc81ls8z0";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/magic-mime/magic-mime.1.3.1";
        hash = "sha256:0f9nbbdgz22qv8l8sgss1ky9h1smywg74x4ivn95jfbf95mvrmnv";
      };
    };
    menhir = 
    {
      pname = "menhir";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20211128";
        hash = "sha256:181n10r5ml6649ps96djaan41jkdidmif0xm565akfy2hqhg8nj5";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20211128";
        hash = "sha256:11qidk8w61v3v0as3pci4yd8mgipqvbrgizx7ydsnipdyjsyva10";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20211128";
        hash = "sha256:0wwcv1ix6wdzyx1cw7yhxqq9w84cbd8f8dwylrkhvkc23snw2za6";
      };
    };
    metrics = 
    {
      pname = "metrics";
      version = "0.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/metrics/releases/download/v0.4.1/metrics-0.4.1.tbz";
        sha256 = "0k8lqvrwfal5jwy45l0aq1hkrvjv0k30pv5hvc1n3l61nl7w5q3p";
      };
      opamInputs = {
                     inherit (selection) ocaml fmt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/metrics/metrics.0.4.1";
        hash = "sha256:052vfl6yilp8lfnp0xms9hzdszllbsc99gcazllqxmb7r7g0afzf";
      };
    };
    mew = 
    {
      pname = "mew";
      version = "0.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew/archive/0.1.0.tar.gz";
        sha256 = "1rjri9mgfb9gn9fmjn0ax21y9jd9wkvr7mmx2jrlqmzgabmqrlv4";
      };
      opamInputs = 
      {
        inherit (selection) trie result ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew/mew.0.1.0";
        hash = "sha256:15f46gisyjfjxksdnyn0maj9i77r23jzwnp7swim8ck91waz97mg";
      };
    };
    mew_vi = 
    {
      pname = "mew_vi";
      version = "0.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew_vi/archive/0.5.0.tar.gz";
        sha256 = "1nmg3cysglgw4115n5zpz4azrfbnfxkn2kvw73chzs69viygm4m6";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml mew dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew_vi/mew_vi.0.5.0";
        hash = "sha256:1bh8gw9llkipggw2rsw9kvl88w47xkw3dp9w3ajbzmblpnkh0i9s";
      };
    };
    mirage = 
    {
      pname = "mirage";
      version = "4.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage/releases/download/v4.7.0/mirage-4.7.0.tbz";
        sha256 = "1gm5bjbsfkxn07gj07hn13snmb0dk5n3zx8klp29fffyn88c9s5d";
      };
      opamInputs = 
      {
        inherit (selection) uri rresult opam-monorepo ocaml logs ipaddr fpath
        fmt emile dune cmdliner bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage/mirage.4.7.0";
        hash = "sha256:1ww64frmm81qjqbw7sy55g9x2nvhvflfwfmlczpv2qg07dh1lcjw";
      };
    };
    mirage-clock = 
    {
      pname = "mirage-clock";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz";
        sha256 = "0iwqi2381fbi3jlcw424dbhjs4fpisw7qpqzfjx7jg72bdfx25zs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-clock/mirage-clock.4.2.0";
        hash = "sha256:17zha0ciapnnp83n1mj8nw98pm4m4s0hmbhrs3z6ymllfb70s05q";
      };
    };
    mirage-clock-unix = 
    {
      pname = "mirage-clock-unix";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz";
        sha256 = "0iwqi2381fbi3jlcw424dbhjs4fpisw7qpqzfjx7jg72bdfx25zs";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-clock dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-clock-unix/mirage-clock-unix.4.2.0";
        hash = "sha256:07prhpqy65wr18r870affavd26bcn1kdbsrf3ch54rh0jn9d2amj";
      };
    };
    mirage-crypto = 
    {
      pname = "mirage-crypto";
      version = "0.11.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.3/mirage-crypto-0.11.3.tbz";
        sha256 = "1ccmbmx478glnsw93cn07816ggfg0ws9yi72qzmhbncw2vx31ddz";
      };
      opamInputs = 
      {
        inherit (selection) ocaml eqaf dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto/mirage-crypto.0.11.3";
        hash = "sha256:0i6prdrk9irghrbfc5w7kqw1z8cbch6xrwfs00r7hd7ffxrxhi9h";
      };
    };
    mirage-crypto-ec = 
    {
      pname = "mirage-crypto-ec";
      version = "0.11.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.3/mirage-crypto-0.11.3.tbz";
        sha256 = "1ccmbmx478glnsw93cn07816ggfg0ws9yi72qzmhbncw2vx31ddz";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto-rng mirage-crypto eqaf
        dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-ec/mirage-crypto-ec.0.11.3";
        hash = "sha256:1pr5g1j9d163frpzrc4c7z25d00vmnhvvka3yg0sryb14dhwzbsl";
      };
    };
    mirage-crypto-pk = 
    {
      pname = "mirage-crypto-pk";
      version = "0.11.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.3/mirage-crypto-0.11.3.tbz";
        sha256 = "1ccmbmx478glnsw93cn07816ggfg0ws9yi72qzmhbncw2vx31ddz";
      };
      opamInputs = 
      {
        inherit (selection) zarith sexplib0 ocaml mirage-crypto-rng
        mirage-crypto eqaf dune cstruct conf-gmp-powm-sec;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-pk/mirage-crypto-pk.0.11.3";
        hash = "sha256:02126vjgk70q170h1mb4rxmdalwfmiqjykcksqxpn4639fpnkcc0";
      };
    };
    mirage-crypto-rng = 
    {
      pname = "mirage-crypto-rng";
      version = "0.11.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.3/mirage-crypto-0.11.3.tbz";
        sha256 = "1ccmbmx478glnsw93cn07816ggfg0ws9yi72qzmhbncw2vx31ddz";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto logs duration
        dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.11.3";
        hash = "sha256:1y1p40n6mz7llysqqp9x7i0ndfm0ar0n770af3bfj52dasg5f0vz";
      };
    };
    mirage-crypto-rng-lwt = 
    {
      pname = "mirage-crypto-rng-lwt";
      version = "0.11.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.3/mirage-crypto-0.11.3.tbz";
        sha256 = "1ccmbmx478glnsw93cn07816ggfg0ws9yi72qzmhbncw2vx31ddz";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mtime mirage-crypto-rng mirage-crypto lwt
        logs duration dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-rng-lwt/mirage-crypto-rng-lwt.0.11.3";
        hash = "sha256:1hqkh47wpfg67i74lrpwkhvsbp7l93v4md5jass5z1jgrfzl97n6";
      };
    };
    mirage-flow = 
    {
      pname = "mirage-flow";
      version = "4.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-flow/releases/download/v4.0.2/mirage-flow-4.0.2.tbz";
        sha256 = "0npvxbg7mlxwpgc2lhbl4si913yw4piicm234jyp7rqv5vfy6ra8";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-flow/mirage-flow.4.0.2";
        hash = "sha256:0shcca2j7vn57lnzy8j41xsisv2640r25vfdbhv3a14rai2jkjdx";
      };
    };
    mirage-net = 
    {
      pname = "mirage-net";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-net/releases/download/v4.0.0/mirage-net-v4.0.0.tbz";
        sha256 = "1kllw58f41qqjnl3iwvz748zk7xqvcahr1sh4jrhl6mqhz8zz3k6";
      };
      opamInputs = 
      {
        inherit (selection) ocaml macaddr lwt fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-net/mirage-net.4.0.0";
        hash = "sha256:1g7285bp2ncbd575r54p4algjykfqchlv6z9476gxvylxl1ncj6a";
      };
    };
    mirage-random = 
    {
      pname = "mirage-random";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-random/releases/download/v3.0.0/mirage-random-v3.0.0.tbz";
        sha256 = "1kv6800zl06hymj0jpydhffv5sdqr5zy9azc4cbwqc343ll3zzj9";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-random/mirage-random.3.0.0";
        hash = "sha256:0mn5ldbf86vyr9w9d90riak823bwgpd6brx718k5qd7w25khyaxw";
      };
    };
    mirage-time = 
    {
      pname = "mirage-time";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-time/releases/download/v3.0.0/mirage-time-v3.0.0.tbz";
        sha256 = "0z5xkhlgyhm22wyhwpf9r0rn4125cc3cxj6ccavyiiz2b2dr8h0d";
      };
      opamInputs = {
                     inherit (selection) ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-time/mirage-time.3.0.0";
        hash = "sha256:1vk2ibpgrxq8njwwqbhznq7zxvwvifp0dracs90drrqikzykdm0d";
      };
    };
    mtime = 
    {
      pname = "mtime";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/mtime/releases/mtime-2.1.0.tbz";
        sha256 = "122dhf4qmba4kfpzljcllgqf5ii8b8ylh6rfazcyl09p5s0b4z09";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mtime/mtime.2.1.0";
        hash = "sha256:02yyxvp5pzyppklsjmb6g69jhs7l2r5n59ac3r7a8r0fs2d509a4";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.5-1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.5.tar.gz";
        sha256 = "16lm2l2j7wmxsz2nb4x1jvjjm48r4ypxqqla032xzqh1as7prq3s";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.5-1";
        hash = "sha256:1qrah9h4s4nhk9ly0v23ny8gp3fs0qx5f9pm79382crrafsspc6d";
      };
      extraSources = [ 
                        {
                          dest = "num-in-findlib-dir.patch";
                          src = pkgs.fetchurl 
                          {
                            url = "https://github.com/ocaml/num/commit/f6e31b1653f32c7c425b69c2b123ab2f924a4d61.patch?full_index=1";
                            sha256 = "01fg0dc5ic95vca3kc8damw2ip2wkq6hx1mc9agj88yq3q1q0f7r";
                          };
                        } ];
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.12.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
        dkml-base-compiler = selection.dkml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.12.1";
        hash = "sha256:0wpdj20ic9w7z1vg4r52xbba8gnlcsbn9dz5jjblbz5wrhsxxvjc";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.12.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.12.1.tar.gz";
        sha256 = "0hbax5bmq8lwyr8868csc8waz8b22fmzr40mgg77md3wan88m97m";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.12.1";
        hash = "sha256:033v60qfa749fhca1b6rzyw8c2ia7fa8zddzgaf89vanmpzah556";
      };
      extraSources = [ 
                        {
                          dest = "alt-signal-stack.patch";
                          src = pkgs.fetchurl 
                          {
                            url = "https://github.com/ocaml/ocaml/commit/1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch?full_index=1";
                            sha256 = "1f9xsk8s7is340lk8yh2n79c0pad05gxqbhkb8qaf70x8riz28vv";
                          };
                        } 
                        {
                          dest = "ocaml-base-compiler.install";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/ocaml-base-compiler/ocaml-base-compiler.install";
                            sha256 = "0y36926faq1qvz6jbi4lq1ajham7c7i15kmn1q53b4aa0jjs3wkr";
                          };
                        } ];
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1rn7ai9n2g5xja553qa5r9iamsqmrsnl4h7zkmmbcn27qj7vczsv";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:1kfvmcdiv7lnlhjpbyv6hij06d3l5222ij7iqfakz15c0zl5nw2k";
      };
      extraSources = [ 
                        {
                          dest = "gen_ocaml_config.ml.in";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/ocaml-config/gen_ocaml_config.ml.in.2";
                            sha256 = "0agx5ijhiiikmbmjllcslj3q47mcgswp5cj4whl60hpw2417rsr2";
                          };
                        } 
                        {
                          dest = "ocaml-config.install";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/ocaml-config/ocaml-config.install";
                            sha256 = "0lbhb7smwnsf57k1sa09f60xgryv901gv2n0sc7assyf9hzxjkvf";
                          };
                        } ];
    };
    ocaml-lsp-server = 
    {
      pname = "ocaml-lsp-server";
      version = "1.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-lsp/releases/download/1.9.0/jsonrpc-1.9.0.tbz";
        sha256 = "1ac44n6g3rf84gvhcca545avgf9vpkwkkkm0s8ipshfhp4g4jikh";
      };
      opamInputs = 
      {
        inherit (selection) yojson spawn result re ppx_yojson_conv_lib pp
        ocamlformat-rpc-lib ocaml dune-build-info dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-lsp-server/ocaml-lsp-server.1.9.0";
        hash = "sha256:0r5mgkqmyv0lf2m55h8vpc78v86ldiy1d921qh4xi0nyhk36clvc";
      };
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.15.0.tar.gz";
        sha256 = "1jd960q6lgjz9i50xbqdx7scxz2kizni0z942145smqb21ryxxnk";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.15.0";
        hash = "sha256:10bawjwj3wql4sa6hf06w6vwxvks3lcklzac4ff2vjhi8z9n09gm";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:0rbcbv43lraqcmnjrx97kqyw8lvfq21n5ymcpacnkh1z2ch76vq5";
      };
      extraSources = [ 
                        {
                          dest = "0001-Harden-test-for-OCaml-5.patch";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/ocamlfind/0001-Harden-test-for-OCaml-5.patch";
                            sha256 = "1s3zhssvmb0bzf3jlwh2hvxky0c4hls8bhx69lqddy5byzrabk3g";
                          };
                        } ];
    };
    ocamlformat-rpc-lib = 
    {
      pname = "ocamlformat-rpc-lib";
      version = "0.19.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocamlformat/releases/download/0.19.0/ocamlformat-0.19.0.tbz";
        sha256 = "0ihgwl7d489g938m1jvgx8azdgq9f5np5mzqwwya797hx2m4dz32";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlformat-rpc-lib/ocamlformat-rpc-lib.0.19.0";
        hash = "sha256:01g9aphkkk5am2a9j8isg8yjb237q527q6vs28wix12f5fhn1pk6";
      };
    };
    ocamlgraph = 
    {
      pname = "ocamlgraph";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/backtracking/ocamlgraph/releases/download/2.1.0/ocamlgraph-2.1.0.tbz";
        sha256 = "0r9d61yva190bdwyz79az6r2d95nfjq43bsm74wz4g95z4v2r5hg";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlgraph/ocamlgraph.2.1.0";
        hash = "sha256:1k5wzpi9z0x59mq4mwq6m4mbpw2qm1467r0nl3y5d5n44c99fa5s";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    odoc = 
    {
      pname = "odoc";
      version = "3.0.0-beta1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/3.0.0_beta1/odoc-3.0.0.beta1.tbz";
        sha256 = "1vq1r999i5q1bymz44k6j0vs95a0vxl94lknsk061djdnp676x13";
      };
      opamInputs = 
      {
        inherit (selection) yojson tyxml result odoc-parser ocaml fpath fmt
        dune crunch cppo cmdliner astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc/odoc.3.0.0~beta1";
        hash = "sha256:19255z318328s9sccsc09kdyq14jb5mbi08gwd25a3s1ndn2wjq9";
      };
    };
    odoc-parser = 
    {
      pname = "odoc-parser";
      version = "3.0.0-beta1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/3.0.0_beta1/odoc-3.0.0.beta1.tbz";
        sha256 = "1vq1r999i5q1bymz44k6j0vs95a0vxl94lknsk061djdnp676x13";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune camlp-streams astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc-parser/odoc-parser.3.0.0~beta1";
        hash = "sha256:16lrss8dxpg1vcc987f69xfnkxxmv8fikid1llkxnwy0d4kg6qyd";
      };
    };
    opam-core = 
    {
      pname = "opam-core";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.3.0.tar.gz";
        sha256 = "16m9a381q3xhn47x402hzzm84gvz1nj0vpc2pvix62s2qj9kqgpf";
      };
      opamInputs = 
      {
        inherit (selection) uutf swhid_core sha re ocamlgraph ocaml jsonm
        dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-core/opam-core.2.3.0";
        hash = "sha256:1sxw62a9jfjyrjf9z53j8r8kdr1v060fpq86k1zanwjjgls4vgq0";
      };
    };
    opam-file-format = 
    {
      pname = "opam-file-format";
      version = "2.1.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam-file-format/archive/refs/tags/2.1.6.tar.gz";
        sha256 = "1hs6qcf2bm1s3pp1jzzsyc82mf79s6dnlkpv92jyyvf38p4qaiwq";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        dune = selection.dune or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-file-format/opam-file-format.2.1.6";
        hash = "sha256:1y89ixri8mqx4sc2prbw8cha06krcvplv6nl0vm5wdfk59sh01qv";
      };
    };
    opam-format = 
    {
      pname = "opam-format";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.3.0.tar.gz";
        sha256 = "16m9a381q3xhn47x402hzzm84gvz1nj0vpc2pvix62s2qj9kqgpf";
      };
      opamInputs = 
      {
        inherit (selection) re opam-file-format opam-core ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-format/opam-format.2.3.0";
        hash = "sha256:1gcvrlkms97jwmqff1y1d2ka0h72whfj3f8l2p3d707gx5qz3w34";
      };
    };
    opam-installer = 
    {
      pname = "opam-installer";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.3.0.tar.gz";
        sha256 = "16m9a381q3xhn47x402hzzm84gvz1nj0vpc2pvix62s2qj9kqgpf";
      };
      opamInputs = 
      {
        inherit (selection) opam-format ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-installer/opam-installer.2.3.0";
        hash = "sha256:04wz7mgrs9rlhdvmpynqs6qbpr6b52f5rk8b7g6y3wgp79bv6z2l";
      };
    };
    opam-monorepo = 
    {
      pname = "opam-monorepo";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/tarides/opam-monorepo/releases/download/0.4.0/opam-monorepo-0.4.0.tbz";
        sha256 = "1hpaqv1a1slmg293vivd2kxl5993pq51kc8s1082802b1wvqdb2z";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-monorepo/opam-monorepo.0.4.0";
        hash = "sha256:0a1dqps2lph6dlds4aiv0ws4bydi84hnanm6xz1yac7l9llxx9fb";
      };
    };
    ounit = 
    {
      pname = "ounit";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = {
                     inherit (selection) ounit2 ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit/ounit.2.2.7";
        hash = "sha256:15jq26fb0mcgm2hpm6av39ig5kyvngqkbk52hwg45n7arfbck455";
      };
    };
    ounit2 = 
    {
      pname = "ounit2";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims seq ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit2/ounit2.2.2.7";
        hash = "sha256:1bm5vvfyvb2bdjiqih1rxjn3j3qxk7ls83lr65qh0abjiws6s8zj";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/parsexp-v0.15.0.tar.gz";
        sha256 = "14yi8dnmpkp52i44aa2knw7m6ib8s285j0k3i240qz5c28mr1vni";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.15.0";
        hash = "sha256:0iplx26dvqbnp03ivh18gvak7l7khnklw2gfvr6yi3nmkdpgvvn2";
      };
    };
    passe = 
    {
      pname = "passe";
      version = "development";
      src = self.directSrc "passe";
      opamInputs = 
      {
        inherit (selection) tls passe-unix-common passe-common lambda-term;
      };
      opamSrc = "passe.opam";
    };
    passe-common = 
    {
      pname = "passe-common";
      version = "development";
      src = self.directSrc "passe-common";
      opamInputs = 
      {
        inherit (selection) yojson uri tls-lwt rresult react ptime ounit
        ocamlfind ocamlbuild mirage-clock-unix mirage lwt_react lwt_ppx lwt
        logs hex dune conf-python-3 conf-git cohttp base64 astring;
      };
      opamSrc = "passe-common.opam";
      buildInputs = [ (pkgs.gup) ];
    };
    passe-server = 
    {
      pname = "passe-server";
      version = "development";
      src = self.directSrc "passe-server";
      opamInputs = 
      {
        inherit (selection) x509 vdoml tcpip safepass re passe-unix-common
        passe-common opam-installer mirage-crypto js_of_ocaml-ppx js_of_ocaml
        dns-client-lwt conduit;
      };
      opamSrc = "passe-server.opam";
    };
    passe-unix-common = 
    {
      pname = "passe-unix-common";
      version = "development";
      src = self.directSrc "passe-unix-common";
      opamInputs = 
      {
        inherit (selection) extlib cohttp-lwt-unix cohttp-lwt;
      };
      opamSrc = "passe-unix-common.opam";
    };
    pbkdf = 
    {
      pname = "pbkdf";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/abeaumont/ocaml-pbkdf/archive/1.2.0.tar.gz";
        sha256 = "0mvlh5iq4wqdfylxaq64sycxihp5jkjdgrrr9wmrlgk2yrsn3d3v";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pbkdf/pbkdf.1.2.0";
        hash = "sha256:1h4rqx7yjg5zblksvl3qd75viyhasp5hc1k2xs19lxfzrwbkgfj9";
      };
    };
    pecu = 
    {
      pname = "pecu";
      version = "0.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/pecu/releases/download/v0.7/pecu-0.7.tbz";
        sha256 = "0y6pkz7bl63rhlhgdaizlkx4xnak95l6f02468yd6a34n6spfx5d";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pecu/pecu.0.7";
        hash = "sha256:1jssadk2ig92jhfn256n3fm8xa99qxqdxzhzp5lfa8vzr9yyydb3";
      };
    };
    pp = 
    {
      pname = "pp";
      version = "2.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/pp/releases/download/2.0.0/pp-2.0.0.tbz";
        sha256 = "06a4nk6rr4kbkfqsi13azf92y5bnq9qq3q7lvsib94mh30akalc6";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pp/pp.2.0.0";
        hash = "sha256:0iik1vlj7ayj58qg8a4kq4gw4f23d7fgkm3v80czi7lflrlxbwfq";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:181w3banl19k1qglqbs2diz45l8w9snf1k1p24zhgwxasj6i2k8r";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "179f1iz504l008b3p3d9q2nj44wv7y31pc997x32m6aq1j2lfip3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.15.1";
        hash = "sha256:17303ra9w8cngiaz0s9q6d8617vyfx2nlz1kb813bs0g4vnj27mf";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_yojson_conv_lib-v0.15.0.tar.gz";
        sha256 = "115nlv3apiwsbay6188916zddpf84bnqdcbrygqw2vjnykpwblpr";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.15.0";
        hash = "sha256:07pckbhr0nbswij1z61mw2qkanz1swp5rns7m04487rkphw2lwa2";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.34.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.34.0/ppxlib-0.34.0.tbz";
        sha256 = "19v1crxb2nzvkw1s2z3rgrz7v4p90k6qf0vwdgjpm38mb8b9fzfp";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.34.0";
        hash = "sha256:0w0flcn20f6sma07q01r7ihd66q8i4n3g0q5pw5zqlanhb370x4j";
      };
    };
    psq = 
    {
      pname = "psq";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/pqwy/psq/releases/download/v0.2.1/psq-0.2.1.tbz";
        sha256 = "0i6k5i3dha3b4syz4jpd5fi6dkalas8bhcpfk4blprxb7r9my022";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/psq/psq.0.2.1";
        hash = "sha256:02q8kpskr8ci5h4wbq14m9qr2a1vjk4zivfhi79gnfp8jl92hdyl";
      };
    };
    ptime = 
    {
      pname = "ptime";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/ptime/releases/ptime-1.2.0.tbz";
        sha256 = "1c1swx6h794gcck358nqfzshlfhyw1zb5ji4h1pc63j9vxzp85ln";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ptime/ptime.1.2.0";
        hash = "sha256:129pc7kb0frzw562h9z9560vrvgg6sfmsddnv62syskfs97aan0b";
      };
    };
    randomconv = 
    {
      pname = "randomconv";
      version = "0.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/randomconv/releases/download/v0.1.3/randomconv-v0.1.3.tbz";
        sha256 = "1iv3r0s5kqxs893b0d55f0r62k777haiahfkkvvfbqwgqsm6la4v";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/randomconv/randomconv.0.1.3";
        hash = "sha256:13vagvgvzzwihlxsm65clpsp4c1s15bd24zkbb7f7h20hl681g81";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.12.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.12.0/re-1.12.0.tbz";
        sha256 = "1m6ipbd4si87l3axc6m4qmmvzh9mbriyglyqmfmz9hkj5zr2n7x0";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.12.0";
        hash = "sha256:1rq8vf5c36qdzij1awiw39jp0ih4vknnx54lqiwqwslwsmmzdhh3";
      };
    };
    react = 
    {
      pname = "react";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/react/releases/react-1.2.2.tbz";
        sha256 = "16cg4byj8lfbbw96dhh8sks5y9n1c3fshz7f2p8m7wgisqax7bf4";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/react/react.1.2.2";
        hash = "sha256:1g490xxp05s17a1darsfj1xq8nlp9q2vxrl1x19gnj1k8ln0cy7h";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:1fjxx5xipvv5lqbbib4fa7z8qsmrnbaxlpg7y17ydzzj7ghrl6n5";
      };
    };
    rresult = 
    {
      pname = "rresult";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz";
        sha256 = "0h2mjyzhay1p4k7n0mzaa7hlc7875kiy6m1i3r1n03j6hddpzahi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rresult/rresult.0.7.0";
        hash = "sha256:0hp2slc9c4sxfmiw6l5g22gfd2qyyyks5sap6sr99gxyq0cqbs7k";
      };
    };
    safepass = 
    {
      pname = "safepass";
      version = "3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/darioteixeira/ocaml-safepass/archive/v3.1.tar.gz";
        sha256 = "04ahndliia0cd291b9dp68a7zzjxby0gx249yagfmzhjv9880h0k";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/safepass/safepass.3.1";
        hash = "sha256:12vh7py3kgb5hqh80kaiafa29hcc8dg7a9582735s61lgbjqar48";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:0zfy5h1imj42qzabh8kvp4japihyypnngq3ijnnsa411775n8zv8";
      };
      extraSources = [ 
                        {
                          dest = "META.seq";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/META.seq";
                            sha256 = "1gm25wb1cq90d9b6szmbqwabh49djpqx1xq2bhrzi7jis2s64l79";
                          };
                        } 
                        {
                          dest = "seq.install";
                          src = pkgs.fetchurl 
                          {
                            url = "https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/seq.install";
                            sha256 = "0129wg5mfr8f3xmvwgl9fncx7qq6xcslq366jin2pa6mqk12dygz";
                          };
                        } ];
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/sexplib/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "1g5wxlwrs50r3kgfyqqm608iw0yfrj4ra7s43z05imwj1llpvnkm";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.15.1";
        hash = "sha256:0n3j8px5f2vab0d47p6zm4daymfq7w7n4kfgplprf56gd9w3irvb";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/sexplib0/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "1cv78931di97av82khqwmx5s51mrn9d2b82z0si88gxwndz83kg8";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.15.1";
        hash = "sha256:1l78jhhcy51qrwzf8v6szzsj4m51ar312qjabl2lcp4jvdjzv725";
      };
    };
    sha = 
    {
      pname = "sha";
      version = "1.15.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/djs55/ocaml-sha/releases/download/v1.15.4/sha-1.15.4.tbz";
        sha256 = "1cgiy6y572rzhpr8ni4xgia2lv4865d8miscvzlrr6di74hv3rbd";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sha/sha.1.15.4";
        hash = "sha256:13881p8vnkpv5x4b2bjbx6cm06nir7r4n3ipqpiiij7b64fla3ga";
      };
    };
    spawn = 
    {
      pname = "spawn";
      version = "v0.17.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/spawn/releases/download/v0.17.0/spawn-v0.17.0.tbz";
        sha256 = "0jfzqb8gn2q1a9h7wr31prrgbvy2bwysgkwmj21ad1rk9k6vbyrk";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/spawn/spawn.v0.17.0";
        hash = "sha256:1igx9wf7svpd8210wna03pc9mmslhyr8fiqbx80v4kqsf3gmwlp2";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stringext = 
    {
      pname = "stringext";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stringext/stringext.1.6.0";
        hash = "sha256:01k5gspcs4i7ipghzm2qsxgmyja86nd224achciny46xdjpkchpd";
      };
    };
    swhid_core = 
    {
      pname = "swhid_core";
      version = "0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/swhid_core/archive/refs/tags/0.1.tar.gz";
        sha256 = "1kxwfgvr8cns5xi6y65xl1s29y3a5zx9wahnv7barw69jzmv8647";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/swhid_core/swhid_core.0.1";
        hash = "sha256:0iyhw33g2m0711fvbpsf3zynz76srdrs3vfp03gb4il77wl4xnfk";
      };
    };
    tcpip = 
    {
      pname = "tcpip";
      version = "8.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-tcpip/releases/download/v8.1.0/tcpip-8.1.0.tbz";
        sha256 = "1h59fm6vhsi27ar36m3n1mbx4kz39igkpxhjag3dv2q7z695vfl6";
      };
      opamInputs = 
      {
        inherit (selection) randomconv ocaml mirage-time mirage-random
        mirage-net mirage-flow mirage-clock metrics macaddr-cstruct macaddr
        lwt-dllist lwt lru logs ipaddr-cstruct ipaddr fmt ethernet duration
        dune cstruct-lwt cstruct cmdliner arp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tcpip/tcpip.8.1.0";
        hash = "sha256:0mh8a82x6ja2hk6l1dwqk8bd5zh1fzlvhmiikxx3r2nfmh5i6dg5";
      };
    };
    tls = 
    {
      pname = "tls";
      version = "0.17.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.17.5/tls-0.17.5.tbz";
        sha256 = "06a8ms9ginhgbz22ybhgiiiisacwynix9a1555r8avrspxbqh449";
      };
      opamInputs = 
      {
        inherit (selection) x509 ocaml mirage-crypto-rng mirage-crypto-pk
        mirage-crypto-ec mirage-crypto logs ipaddr hkdf fmt dune domain-name
        cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tls/tls.0.17.5";
        hash = "sha256:102cpij5cyiyprqmd7hf4ywmmjg0v8gmymiq0jgyil10c61d1snn";
      };
    };
    tls-lwt = 
    {
      pname = "tls-lwt";
      version = "0.17.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.17.5/tls-0.17.5.tbz";
        sha256 = "06a8ms9ginhgbz22ybhgiiiisacwynix9a1555r8avrspxbqh449";
      };
      opamInputs = 
      {
        inherit (selection) x509 tls ptime ocaml mirage-crypto-rng-lwt lwt
        dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tls-lwt/tls-lwt.0.17.5";
        hash = "sha256:13ysi45vw5w5l2hsvf0kdrdmfgf8l01bbwi2b3h31nyp2ksa9yxw";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.7";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
        sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.7";
        hash = "sha256:0l45iqmvsqk69afirx3yqkn2pbdr0l1bkxgscxglkm3rry592k93";
      };
    };
    trie = 
    {
      pname = "trie";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/trie/archive/1.0.0.tar.gz";
        sha256 = "1slq4kiwnc723dsaw15ms7xxpqz061v8zck1m6iyc5j2li70by62";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/trie/trie.1.0.0";
        hash = "sha256:0ic1gdgkxjxvcwqclxawcs02ziywk394svcxhrvlb80il3n3q4ai";
      };
    };
    tyxml = 
    {
      pname = "tyxml";
      version = "4.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.6.0/tyxml-4.6.0.tbz";
        sha256 = "1p82r68lxk6wzxihzd620a6kzp27vn548j2cr970l4jfdcy6gsxz";
      };
      opamInputs = 
      {
        inherit (selection) uutf seq re ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml/tyxml.4.6.0";
        hash = "sha256:02pnpfr487d077arnvras1a6p52san6l5xkw0adgaxqpi7cf1cqy";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:0j6xi9mcpzcglbxmd01q0frgzl80cmrpdbifphl9w9w7hjknv3gp";
      };
    };
    uri = 
    {
      pname = "uri";
      version = "4.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
        sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
      };
      opamInputs = 
      {
        inherit (selection) stringext ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri/uri.4.4.0";
        hash = "sha256:1jzwbdw5lp3bv1hw9kdi86d0yzzfg5shp0571kw9gkhypisr7jva";
      };
    };
    uri-sexp = 
    {
      pname = "uri-sexp";
      version = "4.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
        sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri-sexp/uri-sexp.4.4.0";
        hash = "sha256:0vv34q5lxr1s0j282j3sgvkhspyn37rwa5n48y790w5a8p39ik21";
      };
    };
    utop = 
    {
      pname = "utop";
      version = "2.15.0-1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/utop/releases/download/2.15.0/utop-2.15.0-1.tar.gz";
        sha256 = "0k90bljj1gfww3xw5bijy3vfyc2d25gnyvq7cv2fzvrn7ib48651";
      };
      opamInputs = 
      {
        inherit (selection) zed xdg react ocamlfind ocaml lwt_react lwt logs
        lambda-term dune cppo base-unix base-threads;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/utop/utop.2.15.0-1";
        hash = "sha256:0mcmzakgq1zfcnyx7v84aka978zhjj9na34ydmb7nkjzgi6wv2z5";
      };
    };
    uucp = 
    {
      pname = "uucp";
      version = "15.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uucp/releases/uucp-15.0.0.tbz";
        sha256 = "0c2k9gkg442l7hnc8rn1vqzn6qh68w9fx7h3nj03n2x90ps98ixc";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        uunf = selection.uunf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uucp/uucp.15.0.0";
        hash = "sha256:0bgf8rrsvnzq9wzlf0grgbz00mhjy5ls6g2az0m41mflxcnaz51j";
      };
    };
    uuseg = 
    {
      pname = "uuseg";
      version = "15.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uuseg/releases/uuseg-15.0.0.tbz";
        sha256 = "1qz130wlmnvb6j7kpvgjlqmdm2jqid4wb1dmrsls4hdm4rp7gk5b";
      };
      opamInputs = 
      {
        inherit (selection) uucp topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuseg/uuseg.15.0.0";
        hash = "sha256:10xmzkzn4dr3mz4xckpsds3klvkfpzfcmg82by5qnhzx8lnwk152";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:11xvrsixdrx2a42nrjj6la925asmg1wd7md5rar2xb3m2cy1j1nf";
      };
    };
    vdoml = 
    {
      pname = "vdoml";
      version = "development";
      src = self.directSrc "vdoml";
      opamInputs = 
      {
        inherit (selection) odoc ocamlfind ocaml lwt_ppx lwt logs
        js_of_ocaml-ppx js_of_ocaml-lwt js_of_ocaml dune conf-python-3;
      };
      opamSrc = "vdoml.opam";
    };
    x509 = 
    {
      pname = "x509";
      version = "0.16.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-x509/releases/download/v0.16.5/x509-0.16.5.tbz";
        sha256 = "16fdii9sffdbrbzzhdfk677rs77h01ffw2v9nagn2zx3zsjjb7hl";
      };
      opamInputs = 
      {
        inherit (selection) ptime pbkdf ocaml mirage-crypto-rng
        mirage-crypto-pk mirage-crypto-ec mirage-crypto logs ipaddr gmap fmt
        dune domain-name cstruct base64 asn1-combinators;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/x509/x509.0.16.5";
        hash = "sha256:1dfban110rar93q1wj42ny21jvbyawkc8rajq05390g96lp03fab";
      };
    };
    xdg = 
    {
      pname = "xdg";
      version = "3.17.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.17.2/dune-3.17.2.tbz";
        sha256 = "0r7al83jwkdfk6qvb53vrlzzfr08gwcydn1ccigfdsfg1vnzxslx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xdg/xdg.3.17.2";
        hash = "sha256:01vy9xymnskyc2d6rliwrcmfzkgxp6syv8zn43arap0rvmkcw1jc";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.2.2/yojson-2.2.2.tbz";
        sha256 = "15f5284wkc34q2vs2m6chzydns0ykik8wi7ns8x75m3rka6avgws";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.2.2";
        hash = "sha256:1vi6sffj0561r3vlc3dhxk0gxj81jyn5vz4b5abci2s37vs6bs2h";
      };
    };
    zarith = 
    {
      pname = "zarith";
      version = "1.14";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/Zarith/archive/release-1.14.tar.gz";
        sha256 = "0n8q9lnlgq17a62qprkzqswg5wyh8vcan7sq10m98lwijfyxrfax";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-pkg-config conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zarith/zarith.1.14";
        hash = "sha256:1wmqfdp7j6kmy6g59958qy0ab1fhpz6a17kwfz03g36hphm11v4g";
      };
    };
    zed = 
    {
      pname = "zed";
      version = "3.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/zed/archive/refs/tags/3.2.3.tar.gz";
        sha256 = "13057gf7z2zl4wps8mzf84pm7y52p5z0vzv9zrlp4cl2ss2k0sjb";
      };
      opamInputs = 
      {
        inherit (selection) uutf uuseg uucp uchar result react ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zed/zed.3.2.3";
        hash = "sha256:11pgssqmpr49z1ibnl2hakkdaznhna7nc2zzyhd04x94wnmmk9cm";
      };
    };
  };
}

