### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "86451166382951d5771ad0868b59d5971a95edc7";
          sha256 = "0072arl6i9bzizbvvm3frjhbyi33a14kl1plcaixyg1jjx4lyxql";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.12.1";
  selection = 
  {
    angstrom = 
    {
      pname = "angstrom";
      version = "0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/angstrom/archive/0.16.0.tar.gz";
        sha256 = "1w0hhkdnsbyhpkkacyj5k7dbvy5n3idzkcryr057rm862g9hp0a7";
      };
      opamInputs = 
      {
        inherit (selection) ocaml-syntax-shims ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/angstrom/angstrom.0.16.0";
        hash = "sha256:11h41rci304yznw6v9l2kag6vs4lfn0zcd9mcx8mnjpb4hq05lfh";
      };
    };
    asn1-combinators = 
    {
      pname = "asn1-combinators";
      version = "0.2.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.2.5/asn1-combinators-v0.2.5.tbz";
        sha256 = "1pbcdwm12hnfpd1jv2b7cjfkj5r7h61xp2gr8dysb8waa455kwln";
      };
      opamInputs = 
      {
        inherit (selection) zarith stdlib-shims ptime ocaml dune cstruct
        bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/asn1-combinators/asn1-combinators.0.2.5";
        hash = "sha256:06jazvq72g0kjhcy1h1igv0r8sfh66ahjxvxqg1g97kf2s6hx5lm";
      };
    };
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/v0.14.3.tar.gz";
        sha256 = "0nmydvlbw124c0qz80fx1rpggpr00ylp2zpnyn26qf1a0pfw0kg3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.14.3";
        hash = "sha256:1v61rsyfwkpla41ga6hsagzjihmn1lg5whg2gwb01w9xhdy95qd2";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base64 = 
    {
      pname = "base64";
      version = "3.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz";
        sha256 = "1vb53ijh098d8x0d5a2c7x9ar2j7vll5k2y0mkkylbyikfjxmznq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base64/base64.3.5.1";
        hash = "sha256:0qw6lbd3fjpdll98ihhwzry3xdd2syr545rnbb8fxffzwkpn7nwa";
      };
    };
    bigarray-compat = 
    {
      pname = "bigarray-compat";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/bigarray-compat/releases/download/v1.1.0/bigarray-compat-1.1.0.tbz";
        sha256 = "1m8q6ywik6h0wrdgv8ah2s617y37n1gdj4qvc86yi12winj6ji23";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigarray-compat/bigarray-compat.1.1.0";
        hash = "sha256:1hq7lmh99p720plkbv1faqqz2xz4ff9g49kkpsryg9ws3ld8ry05";
      };
    };
    bigstringaf = 
    {
      pname = "bigstringaf";
      version = "0.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.9.1.tar.gz";
        sha256 = "02smd8d2iv47r5a150nj3angxfp1vwc5474la1jqp68lsrvr5yc7";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigstringaf/bigstringaf.0.9.1";
        hash = "sha256:1f0g6rfnws5pkimpm11pnr8xnq1jw2vhajv6czg3j2n2qndag3a8";
      };
    };
    bos = 
    {
      pname = "bos";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/bos/releases/bos-0.2.1.tbz";
        sha256 = "0dwg7lpaq30rvwc5z1gij36fn9xavvpah1bj8ph9gmhhddw2xmnq";
      };
      opamInputs = 
      {
        inherit (selection) topkg rresult ocamlfind ocamlbuild ocaml logs
        fpath fmt base-unix astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bos/bos.0.2.1";
        hash = "sha256:112gl185kjqmkjk54crcimdnpnzf7g1k35srzpkvc4z79x2j0myd";
      };
    };
    ca-certs = 
    {
      pname = "ca-certs";
      version = "0.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ca-certs/releases/download/v0.2.3/ca-certs-0.2.3.tbz";
        sha256 = "170fqqprqg6nxmc4y8905vwmcbzcwlxjzy6yhgbzcpligm2xdn6j";
      };
      opamInputs = 
      {
        inherit (selection) x509 ptime ocaml mirage-crypto logs fpath dune
        bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ca-certs/ca-certs.0.2.3";
        hash = "sha256:1rsb6c398yvq7p13nggmslc3441h06m3ccjh34ckarc64k2yz4w1";
      };
      buildInputs = [ (pkgs.ca_root_nss or null) ];
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
      };
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/cmdliner/releases/cmdliner-1.2.0.tbz";
        sha256 = "0y00vnlk3nim8bh4gvimdpg71gp22z3b35sfyvb4yf98j1c11vdg";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.2.0";
        hash = "sha256:0q1n1rg7pg34h75k02dmfpcwnhcih1hxaiifzi99ac9yhz6k4wg4";
      };
    };
    cohttp = 
    {
      pname = "cohttp";
      version = "6.0.0-beta2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0_beta2/cohttp-v6.0.0_beta2.tbz";
        sha256 = "05xh4hvjy90mqslwd0q6sa2h99f0p7vb4cf0f911nhc0sn5yrv4h";
      };
      opamInputs = 
      {
        inherit (selection) uri-sexp uri stringext sexplib0 re ppx_sexp_conv
        ocaml logs http dune base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp/cohttp.6.0.0~beta2";
        hash = "sha256:04aa53k6r1fmc30b1rhcnb4bk3p3pjsni4haq354yqydbac8ccnb";
      };
    };
    cohttp-lwt = 
    {
      pname = "cohttp-lwt";
      version = "6.0.0-beta2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0_beta2/cohttp-v6.0.0_beta2.tbz";
        sha256 = "05xh4hvjy90mqslwd0q6sa2h99f0p7vb4cf0f911nhc0sn5yrv4h";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv ocaml lwt logs http
        dune cohttp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt/cohttp-lwt.6.0.0~beta2";
        hash = "sha256:1plhbq85b4j1sr7q3y4krmpnq4zr4s2h8x00z2msrvfsab43lzfm";
      };
    };
    cohttp-lwt-unix = 
    {
      pname = "cohttp-lwt-unix";
      version = "6.0.0-beta2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0_beta2/cohttp-v6.0.0_beta2.tbz";
        sha256 = "05xh4hvjy90mqslwd0q6sa2h99f0p7vb4cf0f911nhc0sn5yrv4h";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_conv ocaml magic-mime lwt logs http fmt
        dune conduit-lwt-unix conduit-lwt cohttp-lwt cohttp cmdliner
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0~beta2";
        hash = "sha256:03h0p1pk502vpa6vz8bvqg1vg6l7w86w2ga84wva2fdbk5nm5w8g";
      };
    };
    conduit = 
    {
      pname = "conduit";
      version = "6.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.1/conduit-6.2.1.tbz";
        sha256 = "1fsvyp1gsyjqm3ycxr43qqwyy15cj3zi3kkr1fdligip4jvfgmar";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib ppx_sexp_conv ocaml logs ipaddr-sexp
        ipaddr dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit/conduit.6.2.1";
        hash = "sha256:1gx62xj26r03pr84pss0zzbmkd0g2km4sns1dbxj0wl8xlg0ysim";
      };
    };
    conduit-lwt = 
    {
      pname = "conduit-lwt";
      version = "6.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.1/conduit-6.2.1.tbz";
        sha256 = "1fsvyp1gsyjqm3ycxr43qqwyy15cj3zi3kkr1fdligip4jvfgmar";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ppx_sexp_conv ocaml lwt dune conduit
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt/conduit-lwt.6.2.1";
        hash = "sha256:0cm6908fyvgq91mkcg707npn16v287cay2m46ly9r7plmbms7q99";
      };
    };
    conduit-lwt-unix = 
    {
      pname = "conduit-lwt-unix";
      version = "6.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v6.2.1/conduit-6.2.1.tbz";
        sha256 = "1fsvyp1gsyjqm3ycxr43qqwyy15cj3zi3kkr1fdligip4jvfgmar";
      };
      opamInputs = 
      {
        inherit (selection) uri ppx_sexp_conv ocaml lwt logs ipaddr-sexp
        ipaddr dune conduit-lwt ca-certs
        base-unix;
        tls-lwt = selection.tls-lwt or null;
        lwt_ssl = selection.lwt_ssl or null;
        launchd = selection.launchd or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt-unix/conduit-lwt-unix.6.2.1";
        hash = "sha256:0fl23bkm1b83i371dfshl8ip6sg0yd85bzvklx2d00jhzzxvj355";
      };
    };
    conf-git = 
    {
      pname = "conf-git";
      version = "1.1";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-git/conf-git.1.1";
        hash = "sha256:1jxl5dls1xjav00g4dmirk11jvv27bk9az21ngl14ybibzsqf67y";
      };
      buildInputs = [ (pkgs.git) ];
    };
    conf-gmp = 
    {
      pname = "conf-gmp";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp/conf-gmp.4";
        hash = "sha256:0n7cazhsgifli8055ylnzcwd716h6x3nx9f3rr2807xj47rfvy0l";
      };
      buildInputs = [ (pkgs.gmp) ];
    };
    conf-gmp-powm-sec = 
    {
      pname = "conf-gmp-powm-sec";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.3";
        hash = "sha256:1q9c4av0ah791sq81yva4ga1mz5380r4260bjh060d3mzci00hd3";
      };
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "3";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.3";
        hash = "sha256:1k66rzbfc38k38wpzq6qp0072x3lmjv47b7jxshmhi9y76q0lawh";
      };
      buildInputs = [ (pkgs.pkg-config) ];
    };
    conf-python-2-7 = 
    {
      pname = "conf-python-2-7";
      version = "1.2";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-python-2-7/conf-python-2-7.1.2";
        hash = "sha256:1jkqfy7h4rl7g59qk5zgh19y8c24xb5c4sjhis0y5m838pgg46f5";
      };
      buildInputs = [ (pkgs.python27) ];
    };
    conf-python-3 = 
    {
      pname = "conf-python-3";
      version = "9.0.0";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-python-3/conf-python-3.9.0.0";
        hash = "sha256:03gbdbwmy3bax7q81dbanfy6mxsmnz05ky7h2qm1g5gjmm8i2bvl";
      };
      buildInputs = [ (pkgs.python3) ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
        sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.9";
        hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
      };
    };
    crunch = 
    {
      pname = "crunch";
      version = "3.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-crunch/releases/download/v3.3.1/crunch-3.3.1.tbz";
        sha256 = "0spdm3znj6r705sd86lcz31qfx2aqjvaykms3irvgjqb27aa0nrc";
      };
      opamInputs = 
      {
        inherit (selection) ptime ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/crunch/crunch.3.3.1";
        hash = "sha256:04zkajphh0yybhpcp7sw16h0wpmmgjx3gbs7rwq70il6hsj7p6aw";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    cstruct = 
    {
      pname = "cstruct";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v5.2.0/cstruct-v5.2.0.tbz";
        sha256 = "0xbajlc21m0rqpzzwp3aixv8g432ipv3kjh7iiiwq25b7xsz7zkb";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct/cstruct.5.2.0";
        hash = "sha256:19jq92g73vdzcfamfrjh3bcsimg950fs4cpxv8by7zbl0mxw9pps";
      };
    };
    cstruct-lwt = 
    {
      pname = "cstruct-lwt";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v5.2.0/cstruct-v5.2.0.tbz";
        sha256 = "0xbajlc21m0rqpzzwp3aixv8g432ipv3kjh7iiiwq25b7xsz7zkb";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt dune cstruct base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct-lwt/cstruct-lwt.5.2.0";
        hash = "sha256:18scxkr4xgchpp2ssz4afryp8i1x38rsdsy36xg3i522lkq1sqkv";
      };
    };
    cstruct-sexp = 
    {
      pname = "cstruct-sexp";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v5.2.0/cstruct-v5.2.0.tbz";
        sha256 = "0xbajlc21m0rqpzzwp3aixv8g432ipv3kjh7iiiwq25b7xsz7zkb";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct-sexp/cstruct-sexp.5.2.0";
        hash = "sha256:035hb7sigjdih5sj6avcxj4jixm2glcfamfg2924g9ad6crsizxh";
      };
    };
    dns = 
    {
      pname = "dns";
      version = "1.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v1.1.3/dns-v1.1.3.tbz";
        sha256 = "0sj5npzdjpgaa33ccbkrp6xnfffzqny9fcr1p8a8z161sw3vb8qp";
      };
      opamInputs = 
      {
        inherit (selection) uri result re ppx_cstruct ocaml ipaddr hashcons
        dune domain-name cstruct base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns/dns.1.1.3";
        hash = "sha256:1b0acdj8lr7kx7bq7k9n0q3ax8ympbfd0p6rd72xq8mphpj17idp";
      };
    };
    dns-lwt = 
    {
      pname = "dns-lwt";
      version = "1.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v1.1.3/dns-v1.1.3.tbz";
        sha256 = "0sj5npzdjpgaa33ccbkrp6xnfffzqny9fcr1p8a8z161sw3vb8qp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-profile lwt dune dns;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns-lwt/dns-lwt.1.1.3";
        hash = "sha256:1j030sja3b3ck7x82cglairrva6dsi8797rgbsjpv3nw578q0rrr";
      };
    };
    dns-lwt-unix = 
    {
      pname = "dns-lwt-unix";
      version = "1.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-dns/releases/download/v1.1.3/dns-v1.1.3.tbz";
        sha256 = "0sj5npzdjpgaa33ccbkrp6xnfffzqny9fcr1p8a8z161sw3vb8qp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune dns-lwt cmdliner base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dns-lwt-unix/dns-lwt-unix.1.1.3";
        hash = "sha256:0dfj00fm3k321jy63ph2fzmk2jcbqb7nba3v2860lihxpblsr80l";
      };
    };
    domain-name = 
    {
      pname = "domain-name";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/domain-name/releases/download/v0.4.0/domain-name-0.4.0.tbz";
        sha256 = "1i8846nw81w0dkd76y0a3jw1sk9734qgw4p8fccj15aqhhi6xh55";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/domain-name/domain-name.0.4.0";
        hash = "sha256:1m9bf04jaqqj67vs6k14q1a46gis95lgzs6vjcfj3cq2j7xj5x0c";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.14.2";
        hash = "sha256:04m2slbrrz471qfi1zds89k02q0a4ka6jsas5prw8bjh2yn77g3h";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.14.2";
        hash = "sha256:1rywdkjcgi56an7a932mhlhw8m2dwlnq647rl1rzjf451hr6sfvg";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.14.2";
        hash = "sha256:06hqqcs8xvzicmvnll8bzm4ww4k2d7hcxdjs6hc3ki7495cx978q";
      };
    };
    duration = 
    {
      pname = "duration";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/duration/releases/download/v0.2.1/duration-0.2.1.tbz";
        sha256 = "0aqyqzkrkkn33jysq3nmy0l24jyy37wdvlqw286856gvikrw2f67";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/duration/duration.0.2.1";
        hash = "sha256:1d7922cvnnccck7kr2dss0d922f17nxsqhygszw5hn5xyirldbpy";
      };
    };
    emile = 
    {
      pname = "emile";
      version = "1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/emile/releases/download/v1.1/emile-v1.1.tbz";
        sha256 = "0r1141makr0b900aby1gn0fccjv1qcqgyxib3bzq8fxmjqwjan8p";
      };
      opamInputs = 
      {
        inherit (selection) uutf pecu ocaml ipaddr dune bigstringaf base64
        angstrom;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/emile/emile.1.1";
        hash = "sha256:1ncaci71knizw15p79gfy1g9vqpm2lk352k59s90hb47kyyv4ykn";
      };
    };
    eqaf = 
    {
      pname = "eqaf";
      version = "0.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/eqaf/releases/download/v0.9/eqaf-0.9.tbz";
        sha256 = "1q6zanrbj0ddrxwhwqdv1223mbk1k5dg0m2qbpwifs5c8sljh3pc";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/eqaf/eqaf.0.9";
        hash = "sha256:12yfvhy9n7qmfy8z6ppz15s13n9l3n0pqpyqms5kalqwcfnxaf7i";
      };
    };
    ethernet = 
    {
      pname = "ethernet";
      version = "2.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ethernet/releases/download/v2.2.0/ethernet-v2.2.0.tbz";
        sha256 = "0qzisqibx2gd8rh330n642mk5wz229199rnlrs7x8cr5pnymif7z";
      };
      opamInputs = 
      {
        inherit (selection) rresult ppx_cstruct ocaml mirage-protocols
        mirage-profile mirage-net macaddr lwt logs fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ethernet/ethernet.2.2.0";
        hash = "sha256:1215y4q45p2lx5z0ggccb58y9sk43c1gk9hkb7lncqzcphf14fzr";
      };
    };
    extlib = 
    {
      pname = "extlib";
      version = "1.7.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ygrek/ocaml-extlib/releases/download/1.7.9/extlib-1.7.9.tar.gz";
        sha256 = "1jydzw2n84cfiz9y6lk4gih4wbr8jybanmiryfs01svd07g4vpjq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/extlib/extlib.1.7.9";
        hash = "sha256:0ms1f9ql8p3n6m81k3hc7xpid0cz2i4f0bpag6gixpmr06qw6inw";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
        sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.9.0";
        hash = "sha256:1czh5i3i4mkf9xfasji3v7n821qmnnandlklh67ali0x87brldny";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    functoria = 
    {
      pname = "functoria";
      version = "4.4.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage/releases/download/v4.4.2/mirage-4.4.2.tbz";
        sha256 = "1yd03ggmwiy5yh09kmifmm14mc2bdwhk40cyddgq360qj6xniwkw";
      };
      opamInputs = 
      {
        inherit (selection) uri rresult result ocaml logs fpath fmt emile
        dune cmdliner bos base-unix astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/functoria/functoria.4.4.2";
        hash = "sha256:18i73apvl2pasdx9p0gmdjyia4cfm6ww7adzzyzl879zzm5wyfgd";
      };
    };
    functoria-runtime = 
    {
      pname = "functoria-runtime";
      version = "4.4.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage/releases/download/v4.4.2/mirage-4.4.2.tbz";
        sha256 = "1yd03ggmwiy5yh09kmifmm14mc2bdwhk40cyddgq360qj6xniwkw";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/functoria-runtime/functoria-runtime.4.4.2";
        hash = "sha256:1cxsnj1igypp30669rgnjdaqrp1aszm2pp2rzv2jji4m0k7kxq95";
      };
    };
    gmap = 
    {
      pname = "gmap";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz";
        sha256 = "073wa0lrb0jj706j87cwzf1a8d1ff14100mnrjs8z3xc4ri9xp84";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/gmap/gmap.0.3.0";
        hash = "sha256:1zibwnms9pyvqqchh5mzd48hq32hrs8qcqbai9jwbydnn805ahq5";
      };
    };
    hashcons = 
    {
      pname = "hashcons";
      version = "1.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/backtracking/ocaml-hashcons/releases/download/1.4.0/hashcons-1.4.0.tbz";
        sha256 = "1hm33h7nvy96vqvhbvjxva7ndn6j4ch8rf3369ja4nhzhh57z0kk";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hashcons/hashcons.1.4.0";
        hash = "sha256:1x4iqscn85pa9xglmllk084n2ldzp6aqiscxw7khj5a4cm1127rp";
      };
    };
    hex = 
    {
      pname = "hex";
      version = "1.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-hex/releases/download/v1.5.0/hex-1.5.0.tbz";
        sha256 = "1p5la5rn9nzvjyslysragwz2vjsbd76vac88lc3r61033g5fwrrf";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hex/hex.1.5.0";
        hash = "sha256:0d3sa6fls4yycsjsdf52lzhg7yav3j7ji7p0smm57799gwgfc6a8";
      };
    };
    hkdf = 
    {
      pname = "hkdf";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/ocaml-hkdf/releases/download/v1.0.4/hkdf-v1.0.4.tbz";
        sha256 = "0nzx6vzbc1hh6vx1ly8df4b16lgps6zjpp9mjycsnnn49bddc9mr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hkdf/hkdf.1.0.4";
        hash = "sha256:03wcvwhzxipf71aqsh77ly8iygqd6f0pwy04pcga58rifgiys5m2";
      };
    };
    http = 
    {
      pname = "http";
      version = "6.0.0-beta2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v6.0.0_beta2/cohttp-v6.0.0_beta2.tbz";
        sha256 = "05xh4hvjy90mqslwd0q6sa2h99f0p7vb4cf0f911nhc0sn5yrv4h";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/http/http.6.0.0~beta2";
        hash = "sha256:15pnwhlnphzvznj6065kli1jibv3bwd4xxwrm0p1sqwsnj0r5ca0";
      };
    };
    ipaddr = 
    {
      pname = "ipaddr";
      version = "5.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.1.0/ipaddr-v5.1.0.tbz";
        sha256 = "0nmzdy0xifnbx8k83m1g12qbshm84xzcvbhvfnq3jpqs5hi2i4vy";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml macaddr dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr/ipaddr.5.1.0";
        hash = "sha256:1g5jqwhwy6j9z9sq6yqas7pnsisf0pz4zp6jv1az006f60phdrvn";
      };
    };
    ipaddr-sexp = 
    {
      pname = "ipaddr-sexp";
      version = "5.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.1.0/ipaddr-v5.1.0.tbz";
        sha256 = "0nmzdy0xifnbx8k83m1g12qbshm84xzcvbhvfnq3jpqs5hi2i4vy";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppx_sexp_conv ocaml ipaddr dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr-sexp/ipaddr-sexp.5.1.0";
        hash = "sha256:1j45par6qm7vfc9b8f3iic71m7brn92bqawgdnk212l0zvjldyma";
      };
    };
    js_of_ocaml = 
    {
      pname = "js_of_ocaml";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) uchar ppxlib ocaml js_of_ocaml-compiler dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml/js_of_ocaml.3.9.0";
        hash = "sha256:1q0z0p1knw78yia0wg1svhr767xk5hx3ygffzh3nx254ql7mlqsa";
      };
    };
    js_of_ocaml-compiler = 
    {
      pname = "js_of_ocaml-compiler";
      version = "3.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.1/js_of_ocaml-3.9.1.tbz";
        sha256 = "0ib551kfsjlp9vr3fk36hrbq7xxyl8bj6vcn3ccr0s370bsmgpm6";
      };
      opamInputs = 
      {
        inherit (selection) yojson ppxlib ocaml menhir dune
        cmdliner;
        ocamlfind = selection.ocamlfind or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.9.1";
        hash = "sha256:0s6r62yk169wm208ssnx5d0ljpj1bqrlcqsbg3bx8fqjx2n0840f";
      };
    };
    js_of_ocaml-lwt = 
    {
      pname = "js_of_ocaml-lwt";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt js_of_ocaml-ppx js_of_ocaml
        dune;
        lwt_log = selection.lwt_log or null;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-lwt/js_of_ocaml-lwt.3.9.0";
        hash = "sha256:0cyfqakgmkg3xgmgymvgkm8wx04m2azjkj7r3lza2s3rjaaymk5x";
      };
    };
    js_of_ocaml-ppx = 
    {
      pname = "js_of_ocaml-ppx";
      version = "3.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/3.9.0/js_of_ocaml-3.9.0.tbz";
        sha256 = "0m6b0ywswh340bsywnj1pa2agfal25x9wg0p57g4rw4s11xv3lvl";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml js_of_ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-ppx/js_of_ocaml-ppx.3.9.0";
        hash = "sha256:0dxypkk5gk6f0kh2mf21qqcmzxzb68albcpb1mpvp4pjivfsij60";
      };
    };
    jsonm = 
    {
      pname = "jsonm";
      version = "1.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/jsonm/releases/jsonm-1.0.2.tbz";
        sha256 = "1mkvi88vwn4rxa5ir3k5qhm8h8z15iyd5rp1ycfj0ls0xfgj6aga";
      };
      opamInputs = 
      {
        inherit (selection) uutf topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jsonm/jsonm.1.0.2";
        hash = "sha256:14yyfrcqfwfb7hnc0d9p20m7nrnv3mngvxsf1wpfpx7k35gnv3ad";
      };
    };
    lambda-term = 
    {
      pname = "lambda-term";
      version = "3.3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/lambda-term/archive/refs/tags/3.3.2.tar.gz";
        sha256 = "0jamxgzjy74j2b8jrs1jgrn6vm63nnvzir7hj9hwaynv4dnzai1d";
      };
      opamInputs = 
      {
        inherit (selection) zed react ocaml mew_vi lwt_react lwt logs dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambda-term/lambda-term.3.3.2";
        hash = "sha256:13w19dgjfp148bc857snrvy5pnvd2czwv1jh89dxry52ddswl5xp";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
      };
    };
    lru = 
    {
      pname = "lru";
      version = "0.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/pqwy/lru/releases/download/v0.3.1/lru-0.3.1.tbz";
        sha256 = "1z9nnba2b4q0q0syyqk4790hzxs71la8h2wwhr7j8nvxgb927gkc";
      };
      opamInputs = {
                     inherit (selection) psq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lru/lru.0.3.1";
        hash = "sha256:0g1gp7p8hzw84cdnmwdyvc2bcpjg06sb86fmmmq2sc6qkxs7hnif";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz";
        sha256 = "11dpr0aprqqjgb2n4j4czpw3l0bc8dzy1jqmp2qz3xkih31k241p";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.7.0";
        hash = "sha256:1fpvcmvrkwaz6w5rshgpw37n10dz9js68i553mmjs1g2g6wdpq73";
      };
    };
    lwt-dllist = 
    {
      pname = "lwt-dllist";
      version = "1.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/lwt-dllist/releases/download/v1.0.1/lwt-dllist-v1.0.1.tbz";
        sha256 = "0vms1py6qh0k8vi6n4wnmrfwpi44a4gfgcpq9i8m23gh81gffv78";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt-dllist/lwt-dllist.1.0.1";
        hash = "sha256:0ygfjbnsmjq78qg26iq1vkhgcmj5gg4mi2nhalcgbz8imm1wlhpf";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.2.0.tar.gz";
        sha256 = "0cmim5s7ay72pxpc66bmxmnj5lbg5yvm0ydrpnfh3nyhlcyjphcp";
      };
      opamInputs = 
      {
        inherit (selection) ppx_tools_versioned ocaml-migrate-parsetree ocaml
        lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.0.1";
        hash = "sha256:1vyj489ib60dh5ghvg0zgf5cp1h4720bnrizsiqdh9103sl2lirw";
      };
    };
    lwt_react = 
    {
      pname = "lwt_react";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml lwt dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_react/lwt_react.1.2.0";
        hash = "sha256:0nar357nms1b90rr0iy2pa0m982yibwkbnx71hsz2v16kj9n831g";
      };
    };
    macaddr = 
    {
      pname = "macaddr";
      version = "5.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.1.0/ipaddr-v5.1.0.tbz";
        sha256 = "0nmzdy0xifnbx8k83m1g12qbshm84xzcvbhvfnq3jpqs5hi2i4vy";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr/macaddr.5.1.0";
        hash = "sha256:1m9nldvsmddskkknxakkphhyy1nzmbbl9m4rqf1agkrl7d347s2q";
      };
    };
    macaddr-cstruct = 
    {
      pname = "macaddr-cstruct";
      version = "5.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.1.0/ipaddr-v5.1.0.tbz";
        sha256 = "0nmzdy0xifnbx8k83m1g12qbshm84xzcvbhvfnq3jpqs5hi2i4vy";
      };
      opamInputs = 
      {
        inherit (selection) ocaml macaddr dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr-cstruct/macaddr-cstruct.5.1.0";
        hash = "sha256:1x3sfpcp6nih7r5fkgn2khwwii8lgs0f9mn6dihn0j0yik1r9p4m";
      };
    };
    magic-mime = 
    {
      pname = "magic-mime";
      version = "1.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.3.1/magic-mime-1.3.1.tbz";
        sha256 = "021vy409qq0gzsn4kzr1lvlsax9dcy3y6mwfqpx1xfjxc81ls8z0";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/magic-mime/magic-mime.1.3.1";
        hash = "sha256:0f9nbbdgz22qv8l8sgss1ky9h1smywg74x4ivn95jfbf95mvrmnv";
      };
    };
    menhir = 
    {
      pname = "menhir";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20211128";
        hash = "sha256:181n10r5ml6649ps96djaan41jkdidmif0xm565akfy2hqhg8nj5";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20211128";
        hash = "sha256:11qidk8w61v3v0as3pci4yd8mgipqvbrgizx7ydsnipdyjsyva10";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20211128";
        hash = "sha256:0wwcv1ix6wdzyx1cw7yhxqq9w84cbd8f8dwylrkhvkc23snw2za6";
      };
    };
    mew = 
    {
      pname = "mew";
      version = "0.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew/archive/0.1.0.tar.gz";
        sha256 = "1rjri9mgfb9gn9fmjn0ax21y9jd9wkvr7mmx2jrlqmzgabmqrlv4";
      };
      opamInputs = 
      {
        inherit (selection) trie result ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew/mew.0.1.0";
        hash = "sha256:0g9xms016f909fzbwgxcy0k4xmvr5zk5bhnz66v9vpsiak2qm4s3";
      };
    };
    mew_vi = 
    {
      pname = "mew_vi";
      version = "0.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew_vi/archive/0.5.0.tar.gz";
        sha256 = "1nmg3cysglgw4115n5zpz4azrfbnfxkn2kvw73chzs69viygm4m6";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml mew dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew_vi/mew_vi.0.5.0";
        hash = "sha256:0zsfhxpff78cqk2c81parajb59m7hqf6v8arksxbyfha6mls65hz";
      };
    };
    mirage = 
    {
      pname = "mirage";
      version = "4.4.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage/releases/download/v4.4.2/mirage-4.4.2.tbz";
        sha256 = "1yd03ggmwiy5yh09kmifmm14mc2bdwhk40cyddgq360qj6xniwkw";
      };
      opamInputs = 
      {
        inherit (selection) opam-monorepo ocaml mirage-runtime logs ipaddr
        functoria dune bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage/mirage.4.4.2";
        hash = "sha256:142nvjfdflibymsnbpcd4k46giwyjbj00jcn5fx1iba1sm3dd97x";
      };
    };
    mirage-clock = 
    {
      pname = "mirage-clock";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz";
        sha256 = "0iwqi2381fbi3jlcw424dbhjs4fpisw7qpqzfjx7jg72bdfx25zs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-clock/mirage-clock.4.2.0";
        hash = "sha256:17zha0ciapnnp83n1mj8nw98pm4m4s0hmbhrs3z6ymllfb70s05q";
      };
    };
    mirage-clock-unix = 
    {
      pname = "mirage-clock-unix";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz";
        sha256 = "0iwqi2381fbi3jlcw424dbhjs4fpisw7qpqzfjx7jg72bdfx25zs";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-clock dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-clock-unix/mirage-clock-unix.4.2.0";
        hash = "sha256:07prhpqy65wr18r870affavd26bcn1kdbsrf3ch54rh0jn9d2amj";
      };
    };
    mirage-crypto = 
    {
      pname = "mirage-crypto";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml eqaf dune-configurator dune cstruct
        conf-pkg-config
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto/mirage-crypto.0.10.3";
        hash = "sha256:1hhpk2jzqx60s8jd6x55bn0bg2q3185vjdb6zmf8lmbflp0lms1a";
      };
    };
    mirage-crypto-ec = 
    {
      pname = "mirage-crypto-ec";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto-rng mirage-crypto eqaf
        dune-configurator dune cstruct
        conf-pkg-config;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-ec/mirage-crypto-ec.0.10.3";
        hash = "sha256:1mm0x5xj78381cb7r11abydnmcpwvmbq6gqlqvfkzxiwbhcc9c58";
      };
    };
    mirage-crypto-pk = 
    {
      pname = "mirage-crypto-pk";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) zarith sexplib rresult ppx_sexp_conv ocaml
        mirage-crypto-rng mirage-crypto eqaf dune cstruct
        conf-gmp-powm-sec;
        zarith-freestanding = selection.zarith-freestanding or null;
        mirage-runtime = selection.mirage-runtime or null;
        mirage-no-xen = selection.mirage-no-xen or null;
        mirage-no-solo5 = selection.mirage-no-solo5 or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-pk/mirage-crypto-pk.0.10.3";
        hash = "sha256:0kvrydkagyjicajf5hmcxhkpalarnad8z1si79zb0r6aybn841iq";
      };
    };
    mirage-crypto-rng = 
    {
      pname = "mirage-crypto-rng";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mtime mirage-crypto lwt logs duration
        dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.10.3";
        hash = "sha256:1vp4ilj2axjfka6b2rs3fgjhplalp48f5whir8pxfqxvs9jig8hb";
      };
    };
    mirage-device = 
    {
      pname = "mirage-device";
      version = "2.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-device/releases/download/v2.0.0/mirage-device-v2.0.0.tbz";
        sha256 = "18alxyi6wlxqvb4lajjlbdfkgcajsmklxi9xqmpcz07j51knqa04";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt fmt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-device/mirage-device.2.0.0";
        hash = "sha256:1pd2xi9qn2vks9nadcfz222kkzl7wy01sgqyqcvp6857yn8i0lql";
      };
    };
    mirage-flow = 
    {
      pname = "mirage-flow";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-flow/releases/download/v3.0.0/mirage-flow-v3.0.0.tbz";
        sha256 = "1z1qc5lr2lmy0w43z4cj7d810a4x4rgxki4bv2z4f9zchmndl2yp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-flow/mirage-flow.3.0.0";
        hash = "sha256:0pmhxnpr7zvlba69ib9vclpmp07m6qfndx6wq3x2wj8nfgyx17s4";
      };
    };
    mirage-fs = 
    {
      pname = "mirage-fs";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-fs/releases/download/v4.0.0/mirage-fs-v4.0.0.tbz";
        sha256 = "0yv73l39xr8vrnrk9wga9rjhhnkbmhlizi2f2pwfpi7f4cf7d1ix";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-kv lwt fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-fs/mirage-fs.4.0.0";
        hash = "sha256:13hfajbw6cn42i7l61ql9b0c5vap042r71mhdk23fwv4yczl5myy";
      };
    };
    mirage-fs-unix = 
    {
      pname = "mirage-fs-unix";
      version = "1.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-fs-unix/releases/download/v1.7.0/mirage-fs-unix-v1.7.0.tbz";
        sha256 = "134b997cf24zr7hgz2g5kx047dbbqi3dnc4r17i0x0wg116zf0dw";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-kv mirage-fs lwt dune cstruct-lwt
        cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-fs-unix/mirage-fs-unix.1.7.0";
        hash = "sha256:04z5ik5mpp32zn2rzh7vx1c8n7bgfa0xn94nki4yljmj22v42n97";
      };
    };
    mirage-kv = 
    {
      pname = "mirage-kv";
      version = "4.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-kv/releases/download/v4.0.1/mirage-kv-4.0.1.tbz";
        sha256 = "0wdaandrfp7iq4b5wmik6x2p3vza2szqsj10abkx9ik08p6via57";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt fmt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-kv/mirage-kv.4.0.1";
        hash = "sha256:1w5zp4yliv69pz0kzjnsz2lgl7dhjwx4h63j2wyrcpr9apxlmsw9";
      };
    };
    mirage-net = 
    {
      pname = "mirage-net";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-net/releases/download/v4.0.0/mirage-net-v4.0.0.tbz";
        sha256 = "1kllw58f41qqjnl3iwvz748zk7xqvcahr1sh4jrhl6mqhz8zz3k6";
      };
      opamInputs = 
      {
        inherit (selection) ocaml macaddr lwt fmt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-net/mirage-net.4.0.0";
        hash = "sha256:1g7285bp2ncbd575r54p4algjykfqchlv6z9476gxvylxl1ncj6a";
      };
    };
    mirage-no-solo5 = 
    {
      pname = "mirage-no-solo5";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-solo5/mirage-no-solo5.1";
        hash = "sha256:18h50v7lp39sis6jy46h35vij0v1z5fr76c4y2h4b72c40fwwck1";
      };
    };
    mirage-no-xen = 
    {
      pname = "mirage-no-xen";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-xen/mirage-no-xen.1";
        hash = "sha256:1nvmvay3nkl8ljw9f46dwv3jppqbbkp0pxf9f1gq4spckb8ysmkh";
      };
    };
    mirage-profile = 
    {
      pname = "mirage-profile";
      version = "0.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-profile/releases/download/v0.9.1/mirage-profile-v0.9.1.tbz";
        sha256 = "0lh3591ad4v7nxpd410b75idmgdq668mqdilvkg4avrwqw1wzdib";
      };
      opamInputs = 
      {
        inherit (selection) ppx_cstruct ocplib-endian ocaml lwt dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-profile/mirage-profile.0.9.1";
        hash = "sha256:02gvd3f914s22r3ckpiqyq345fq5vk097brg2zwzfxljibzz94q2";
      };
    };
    mirage-protocols = 
    {
      pname = "mirage-protocols";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-protocols/releases/download/v5.0.0/mirage-protocols-v5.0.0.tbz";
        sha256 = "1bd6zgxhq2qliyzzarfvaj3ksr20ryghxq6h24i2hha7rwim63bk";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-flow mirage-device macaddr lwt
        ipaddr fmt duration dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-protocols/mirage-protocols.5.0.0";
        hash = "sha256:1k6r918djlp7h092n0h45v0pphzfjh8ajs16drmjw7iqx0wphg6c";
      };
    };
    mirage-random = 
    {
      pname = "mirage-random";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-random/releases/download/v3.0.0/mirage-random-v3.0.0.tbz";
        sha256 = "1kv6800zl06hymj0jpydhffv5sdqr5zy9azc4cbwqc343ll3zzj9";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-random/mirage-random.3.0.0";
        hash = "sha256:0w3577cghv5r8c6qi9d7fbjry7ghavi44k2cn3zf2kwy3qml5n51";
      };
    };
    mirage-runtime = 
    {
      pname = "mirage-runtime";
      version = "4.4.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage/releases/download/v4.4.2/mirage-4.4.2.tbz";
        sha256 = "1yd03ggmwiy5yh09kmifmm14mc2bdwhk40cyddgq360qj6xniwkw";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt logs ipaddr functoria-runtime dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-runtime/mirage-runtime.4.4.2";
        hash = "sha256:0ifvxzv3afvvz6ppn9g6xnxrpzkxm3ajvdc66sa9qfm7lk8s05yf";
      };
    };
    mirage-stack = 
    {
      pname = "mirage-stack";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-stack/releases/download/v3.0.0/mirage-stack-v3.0.0.tbz";
        sha256 = "0xzxa9i25y79qngrlffiv01651rxaw0vwac4rpg8fwmvml5al8nj";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-protocols lwt fmt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-stack/mirage-stack.3.0.0";
        hash = "sha256:11mhw6zvk8z7w03zlrcvk5mjylgw2214pnwyjrn47as0plnl9rv0";
      };
    };
    mirage-time = 
    {
      pname = "mirage-time";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-time/releases/download/v3.0.0/mirage-time-v3.0.0.tbz";
        sha256 = "0z5xkhlgyhm22wyhwpf9r0rn4125cc3cxj6ccavyiiz2b2dr8h0d";
      };
      opamInputs = {
                     inherit (selection) ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-time/mirage-time.3.0.0";
        hash = "sha256:1vk2ibpgrxq8njwwqbhznq7zxvwvifp0dracs90drrqikzykdm0d";
      };
    };
    mtime = 
    {
      pname = "mtime";
      version = "2.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/mtime/releases/mtime-2.0.0.tbz";
        sha256 = "1ss4w3qxsfp51d88r0j7dzqs05dbb1xdx11hn1jl9cvd03ma0g9z";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mtime/mtime.2.0.0";
        hash = "sha256:1q4nd8xpl3bqc1avxrkw4gfrk00xw9r4k1xdzavjdkqd2b5szl89";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.5.tar.gz";
        sha256 = "16lm2l2j7wmxsz2nb4x1jvjjm48r4ypxqqla032xzqh1as7prq3s";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.5";
        hash = "sha256:06zrv1r5qn3hl9mpbhkbfckhhk6kysnkl348drvj3dmcg89hgnp8";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.12.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
        dkml-base-compiler = selection.dkml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.12.1";
        hash = "sha256:03nw1pwqi0w8fy7jxfc590pr7jja0mzbjrxs6figmmr6lsk8jlyz";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.12.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.12.1.tar.gz";
        sha256 = "0hbax5bmq8lwyr8868csc8waz8b22fmzr40mgg77md3wan88m97m";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.12.1";
        hash = "sha256:0la5pfc1n77mq36kqwall134knyj8wbfnsdj3yrywpdgly9f8c5g";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1rn7ai9n2g5xja553qa5r9iamsqmrsnl4h7zkmmbcn27qj7vczsv";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-lsp-server = 
    {
      pname = "ocaml-lsp-server";
      version = "1.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-lsp/releases/download/1.9.0/jsonrpc-1.9.0.tbz";
        sha256 = "1ac44n6g3rf84gvhcca545avgf9vpkwkkkm0s8ipshfhp4g4jikh";
      };
      opamInputs = 
      {
        inherit (selection) yojson spawn result re ppx_yojson_conv_lib pp
        ocamlformat-rpc-lib ocaml dune-build-info dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-lsp-server/ocaml-lsp-server.1.9.0";
        hash = "sha256:0r5mgkqmyv0lf2m55h8vpc78v86ldiy1d921qh4xi0nyhk36clvc";
      };
    };
    ocaml-migrate-parsetree = 
    {
      pname = "ocaml-migrate-parsetree";
      version = "1.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/download/v1.8.0/ocaml-migrate-parsetree-v1.8.0.tbz";
        sha256 = "1dcgifw2npgkjrnb1b6jvx36wydy0nk6ny3m4wgh8i0lzxvd3hmi";
      };
      opamInputs = 
      {
        inherit (selection) result ppx_derivers ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.8.0";
        hash = "sha256:0l2wwjqwq9crqj9w4py3wg3zpx5j5nl7sj6yp4fd637181m4qvsl";
      };
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.3.tar.gz";
        sha256 = "1qf21zds8f3izbb9bxwblijgb7wqkrhbl99z1gpcdas147yin5ff";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.3";
        hash = "sha256:0ymzb8ykkbvpzp8swdssr1iw85a0i66vprnxsxy6dpghhpm1rrqs";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
      };
    };
    ocamlformat-rpc-lib = 
    {
      pname = "ocamlformat-rpc-lib";
      version = "0.19.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocamlformat/releases/download/0.19.0/ocamlformat-0.19.0.tbz";
        sha256 = "0ihgwl7d489g938m1jvgx8azdgq9f5np5mzqwwya797hx2m4dz32";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlformat-rpc-lib/ocamlformat-rpc-lib.0.19.0";
        hash = "sha256:01g9aphkkk5am2a9j8isg8yjb237q527q6vs28wix12f5fhn1pk6";
      };
    };
    ocamlgraph = 
    {
      pname = "ocamlgraph";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/backtracking/ocamlgraph/releases/download/2.1.0/ocamlgraph-2.1.0.tbz";
        sha256 = "0r9d61yva190bdwyz79az6r2d95nfjq43bsm74wz4g95z4v2r5hg";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlgraph/ocamlgraph.2.1.0";
        hash = "sha256:1k5wzpi9z0x59mq4mwq6m4mbpw2qm1467r0nl3y5d5n44c99fa5s";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    odoc = 
    {
      pname = "odoc";
      version = "2.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/2.4.1/odoc-2.4.1.tbz";
        sha256 = "1nyfb1si6fvrzfjxyz6wihyvclnhd6lxkl8pgyv3wl0b0aws055q";
      };
      opamInputs = 
      {
        inherit (selection) tyxml result odoc-parser ocaml fpath fmt dune
        crunch cppo cmdliner astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc/odoc.2.4.1";
        hash = "sha256:1k250r12123a3cd5h8gjby6s8c77izdsc7wvhn3p7i7yyc3n819a";
      };
    };
    odoc-parser = 
    {
      pname = "odoc-parser";
      version = "2.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/2.4.1/odoc-2.4.1.tbz";
        sha256 = "1nyfb1si6fvrzfjxyz6wihyvclnhd6lxkl8pgyv3wl0b0aws055q";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune camlp-streams astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc-parser/odoc-parser.2.4.1";
        hash = "sha256:07jngh0dg34fjdrlv3s9xfr43z1n7jykcwz31s5s4fh9y62ycg3j";
      };
    };
    opam-core = 
    {
      pname = "opam-core";
      version = "2.2.0-beta1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.2.0-beta1.tar.gz";
        sha256 = "0v5pff3dl1x4hlbf79sdqix6c4x19xfp5glzppn626vi466zv4pn";
      };
      opamInputs = 
      {
        inherit (selection) uutf swhid_core sha re ocamlgraph ocaml jsonm
        dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-core/opam-core.2.2.0~beta1";
        hash = "sha256:110vkjrdz77sc2fi37lnwrhc7xx1b51lg96lga94c29whs00zc0j";
      };
    };
    opam-file-format = 
    {
      pname = "opam-file-format";
      version = "2.1.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam-file-format/archive/refs/tags/2.1.6.tar.gz";
        sha256 = "1hs6qcf2bm1s3pp1jzzsyc82mf79s6dnlkpv92jyyvf38p4qaiwq";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        dune = selection.dune or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-file-format/opam-file-format.2.1.6";
        hash = "sha256:1y89ixri8mqx4sc2prbw8cha06krcvplv6nl0vm5wdfk59sh01qv";
      };
    };
    opam-format = 
    {
      pname = "opam-format";
      version = "2.2.0-beta1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.2.0-beta1.tar.gz";
        sha256 = "0v5pff3dl1x4hlbf79sdqix6c4x19xfp5glzppn626vi466zv4pn";
      };
      opamInputs = 
      {
        inherit (selection) re opam-file-format opam-core ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-format/opam-format.2.2.0~beta1";
        hash = "sha256:1py6d21zsm24j994gvn6ah4jd40cg3qiji56krbv0q6b87r1q1qw";
      };
    };
    opam-installer = 
    {
      pname = "opam-installer";
      version = "2.2.0-beta1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/opam/archive/refs/tags/2.2.0-beta1.tar.gz";
        sha256 = "0v5pff3dl1x4hlbf79sdqix6c4x19xfp5glzppn626vi466zv4pn";
      };
      opamInputs = 
      {
        inherit (selection) opam-format ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-installer/opam-installer.2.2.0~beta1";
        hash = "sha256:13i806rf16vmlyxdcxd4gx1b0wbrzzryqv9gyzbk2va5xj9x7i44";
      };
    };
    opam-monorepo = 
    {
      pname = "opam-monorepo";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/tarides/opam-monorepo/releases/download/0.4.0/opam-monorepo-0.4.0.tbz";
        sha256 = "1hpaqv1a1slmg293vivd2kxl5993pq51kc8s1082802b1wvqdb2z";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/opam-monorepo/opam-monorepo.0.4.0";
        hash = "sha256:0a1dqps2lph6dlds4aiv0ws4bydi84hnanm6xz1yac7l9llxx9fb";
      };
    };
    ounit = 
    {
      pname = "ounit";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = {
                     inherit (selection) ounit2 ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit/ounit.2.2.7";
        hash = "sha256:15jq26fb0mcgm2hpm6av39ig5kyvngqkbk52hwg45n7arfbck455";
      };
    };
    ounit2 = 
    {
      pname = "ounit2";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims seq ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit2/ounit2.2.2.7";
        hash = "sha256:1bm5vvfyvb2bdjiqih1rxjn3j3qxk7ls83lr65qh0abjiws6s8zj";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/parsexp/archive/refs/tags/v0.14.2.tar.gz";
        sha256 = "0c7jl6sqfawqpvbhci8vyyhgvcyd3lw5lj3jcf5f1p6w1177xqgn";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.14.2";
        hash = "sha256:1fqnxdr1pgxmada77hkhyyr7yybpv2f810shnhvhkpw15h58azx1";
      };
    };
    passe = 
    {
      pname = "passe";
      version = "development";
      src = self.directSrc "passe";
      opamInputs = 
      {
        inherit (selection) tls passe-unix-common passe-common lambda-term;
      };
      opamSrc = "passe.opam";
    };
    passe-common = 
    {
      pname = "passe-common";
      version = "development";
      src = self.directSrc "passe-common";
      opamInputs = 
      {
        inherit (selection) yojson uri rresult react ptime ounit ocamlfind
        ocamlbuild mirage-fs-unix mirage-clock-unix mirage lwt_react lwt_ppx
        lwt logs hex dune conf-python-3 conf-git cohttp base64 astring;
      };
      opamSrc = "passe-common.opam";
      buildInputs = [ (pkgs.gup) ];
    };
    passe-server = 
    {
      pname = "passe-server";
      version = "development";
      src = self.directSrc "passe-server";
      opamInputs = 
      {
        inherit (selection) x509 vdoml tcpip safepass re passe-unix-common
        passe-common opam-installer mirage-crypto js_of_ocaml dns-lwt-unix
        conduit;
      };
      opamSrc = "passe-server.opam";
    };
    passe-unix-common = 
    {
      pname = "passe-unix-common";
      version = "development";
      src = self.directSrc "passe-unix-common";
      opamInputs = 
      {
        inherit (selection) extlib cohttp-lwt-unix cohttp-lwt;
      };
      opamSrc = "passe-unix-common.opam";
    };
    pbkdf = 
    {
      pname = "pbkdf";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/abeaumont/ocaml-pbkdf/releases/download/1.1.0/pbkdf-1.1.0.tbz";
        sha256 = "0r120hysfn4kbbwwv6j7si8avjcbakxi071lia2hqjdzkayx2gp5";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pbkdf/pbkdf.1.1.0";
        hash = "sha256:0acsk9634agacrm44r13ynxmd7z9cb2f2v4jp493prb8blcya544";
      };
    };
    pecu = 
    {
      pname = "pecu";
      version = "0.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/pecu/releases/download/v0.6/pecu-v0.6.tbz";
        sha256 = "1iz5jj9lyl1pah8dfni4wv0qml0ir5zknv4zhw7v50sc8kdbglm9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pecu/pecu.0.6";
        hash = "sha256:0mlph1frfabf13vggcr6jkj1qx5bb3g7sp52k498jn6ylq1w3dcq";
      };
    };
    pp = 
    {
      pname = "pp";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/pp/releases/download/1.2.0/pp-1.2.0.tbz";
        sha256 = "174hwr63gpliw9w2ipzjbkvdib7js6n6xicyn8nv9bsm7ibj5s55";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pp/pp.1.2.0";
        hash = "sha256:01jdpmgn5pagfax63y23z532xl8s2sb6wpcn96fh612azk1fm5li";
      };
    };
    ppx_cstruct = 
    {
      pname = "ppx_cstruct";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v5.2.0/cstruct-v5.2.0.tbz";
        sha256 = "0xbajlc21m0rqpzzwp3aixv8g432ipv3kjh7iiiwq25b7xsz7zkb";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib ppx_tools_versioned
        ocaml-migrate-parsetree ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cstruct/ppx_cstruct.5.2.0";
        hash = "sha256:0hhjlzk2v0q1fka4nzlq8vz5iszg6ipb8zspf7d5kd1qz53ihjwr";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.1.tar.gz";
        sha256 = "0lpm5bjxmrb5r21fqj6w9xdyhb22c40mic5h8pal8d5r9kf4gy6c";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.1";
        hash = "sha256:1nz6i2jp1sgcjc15g5a8qw2cisph3hi385kiziglndmm4wxlsb6d";
      };
    };
    ppx_tools_versioned = 
    {
      pname = "ppx_tools_versioned";
      version = "5.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_tools_versioned/archive/5.4.0.tar.gz";
        sha256 = "0sw2676vgbsj133lgs3sl8494fhfldafzvgw4j4dnb1wqwha6pxy";
      };
      opamInputs = 
      {
        inherit (selection) ocaml-migrate-parsetree ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_tools_versioned/ppx_tools_versioned.5.4.0";
        hash = "sha256:00s2djkd11gyfakk4h0hyidc70dwcm85gv9xzipqmszfiz77104r";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_yojson_conv_lib-v0.15.0.tar.gz";
        sha256 = "115nlv3apiwsbay6188916zddpf84bnqdcbrygqw2vjnykpwblpr";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.15.0";
        hash = "sha256:07pckbhr0nbswij1z61mw2qkanz1swp5rns7m04487rkphw2lwa2";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.15.0/ppxlib-0.15.0.tbz";
        sha256 = "0c5kjgyxhck5wlnhrsh77ylkbrq3rssqhwf2bjjrka3limzhsqqb";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-migrate-parsetree ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.15.0";
        hash = "sha256:0vzvv4wrp5swz1w1kx8q4ypyr8q3brrnsm52rwxqmimizc2aj3xn";
      };
    };
    psq = 
    {
      pname = "psq";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/pqwy/psq/releases/download/v0.2.1/psq-0.2.1.tbz";
        sha256 = "0i6k5i3dha3b4syz4jpd5fi6dkalas8bhcpfk4blprxb7r9my022";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/psq/psq.0.2.1";
        hash = "sha256:02q8kpskr8ci5h4wbq14m9qr2a1vjk4zivfhi79gnfp8jl92hdyl";
      };
    };
    ptime = 
    {
      pname = "ptime";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/ptime/releases/ptime-0.8.5.tbz";
        sha256 = "1fxq57xy1ajzfdnvv5zfm7ap2nf49znw5f9gbi4kb9vds942ij27";
      };
      opamInputs = 
      {
        inherit (selection) topkg result ocamlfind ocamlbuild
        ocaml;
        js_of_ocaml = selection.js_of_ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ptime/ptime.0.8.5";
        hash = "sha256:0fcffdq19kxgk4mq4k0z1cb20f2f44jr7rj6ba5chwsscvz8f76y";
      };
    };
    randomconv = 
    {
      pname = "randomconv";
      version = "0.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/randomconv/releases/download/v0.1.3/randomconv-v0.1.3.tbz";
        sha256 = "1iv3r0s5kqxs893b0d55f0r62k777haiahfkkvvfbqwgqsm6la4v";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/randomconv/randomconv.0.1.3";
        hash = "sha256:13vagvgvzzwihlxsm65clpsp4c1s15bd24zkbb7f7h20hl681g81";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.11.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz";
        sha256 = "0kwdvzb2wy3rxq3mvmsgc8cdwrzka2viysvrmrrbxxn0h13j9z01";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.11.0";
        hash = "sha256:18048c9lw3g8db1r01diljzvla2pj9bw2fcnvq34gnviwi9rxqjf";
      };
    };
    react = 
    {
      pname = "react";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/react/releases/react-1.2.2.tbz";
        sha256 = "16cg4byj8lfbbw96dhh8sks5y9n1c3fshz7f2p8m7wgisqax7bf4";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/react/react.1.2.2";
        hash = "sha256:1airidp9cw8sk92jc3bvarph3pc43qaf3hcywi0anmpznsygcm0z";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    rresult = 
    {
      pname = "rresult";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz";
        sha256 = "0h2mjyzhay1p4k7n0mzaa7hlc7875kiy6m1i3r1n03j6hddpzahi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rresult/rresult.0.7.0";
        hash = "sha256:0131az6qj1086hi1kjc7x99x1q4c0z3axjwd1wbmr6c6r6nnaj6y";
      };
    };
    safepass = 
    {
      pname = "safepass";
      version = "3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/darioteixeira/ocaml-safepass/archive/v3.1.tar.gz";
        sha256 = "04ahndliia0cd291b9dp68a7zzjxby0gx249yagfmzhjv9880h0k";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/safepass/safepass.3.1";
        hash = "sha256:12vh7py3kgb5hqh80kaiafa29hcc8dg7a9582735s61lgbjqar48";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib-v0.14.0.tar.gz";
        sha256 = "12rlnc6fcrjfdn3gs2agi418sj54ighhs6dfll37zcv7mgywblm2";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.14.0";
        hash = "sha256:1nlzjkx60d4z09b15nq35ivzl6akk3svq7nl4vv5swhsmj8gvpl4";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.14.0";
        hash = "sha256:10glyvk126lw284rfrxj6yj4a60s2l6b6cj2w1cxc7m8hwqh1p9r";
      };
    };
    sha = 
    {
      pname = "sha";
      version = "1.15.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/djs55/ocaml-sha/releases/download/v1.15.4/sha-1.15.4.tbz";
        sha256 = "1cgiy6y572rzhpr8ni4xgia2lv4865d8miscvzlrr6di74hv3rbd";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sha/sha.1.15.4";
        hash = "sha256:13881p8vnkpv5x4b2bjbx6cm06nir7r4n3ipqpiiij7b64fla3ga";
      };
    };
    spawn = 
    {
      pname = "spawn";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/spawn/archive/v0.15.1.tar.gz";
        sha256 = "0l4xq43dxsvxli9kkpnywrw81dyn11bfpdlsd36kyv5b9wqyxzcs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/spawn/spawn.v0.15.1";
        hash = "sha256:18cl7lgcf5gl3r5ffdqiza5hydjgn8hwk4lsb6gsibv8jd7jx8bq";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stringext = 
    {
      pname = "stringext";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stringext/stringext.1.6.0";
        hash = "sha256:01k5gspcs4i7ipghzm2qsxgmyja86nd224achciny46xdjpkchpd";
      };
    };
    swhid_core = 
    {
      pname = "swhid_core";
      version = "0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/swhid_core/archive/refs/tags/0.1.tar.gz";
        sha256 = "1kxwfgvr8cns5xi6y65xl1s29y3a5zx9wahnv7barw69jzmv8647";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/swhid_core/swhid_core.0.1";
        hash = "sha256:0iyhw33g2m0711fvbpsf3zynz76srdrs3vfp03gb4il77wl4xnfk";
      };
    };
    tcpip = 
    {
      pname = "tcpip";
      version = "6.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-tcpip/releases/download/v6.2.0/tcpip-v6.2.0.tbz";
        sha256 = "06qy2nksvkknczfldp5bwxklznrc8ar5lz4pby6q1nh4rr1ydxnh";
      };
      opamInputs = 
      {
        inherit (selection) rresult randomconv ppx_cstruct ocaml mirage-time
        mirage-stack mirage-random mirage-protocols mirage-profile mirage-net
        mirage-flow mirage-clock macaddr-cstruct macaddr lwt-dllist lwt lru
        logs ipaddr fmt ethernet duration dune cstruct-lwt cstruct
        conf-pkg-config;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tcpip/tcpip.6.2.0";
        hash = "sha256:1drnm805450nz3r6nn7v5wqjn84wns8a05y8kvlfznrn9zlhfihf";
      };
    };
    tls = 
    {
      pname = "tls";
      version = "0.13.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.13.2/tls-v0.13.2.tbz";
        sha256 = "0iz7jgrgj4nn84wg8v61zvx8c01pb2rihg7kczjhvw56yyx8aki0";
      };
      opamInputs = 
      {
        inherit (selection) x509 sexplib rresult ptime ppx_sexp_conv
        ppx_cstruct ocaml mirage-crypto-rng mirage-crypto-pk mirage-crypto-ec
        mirage-crypto lwt logs hkdf fmt dune domain-name cstruct-sexp
        cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tls/tls.0.13.2";
        hash = "sha256:11mb56m7mqjdgmgz1l3bkyxynrd49mqakp8rqcmqvzww4skwp8c2";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.7";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
        sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.7";
        hash = "sha256:1411142m653308lj3nlgbv2wvww2i5hyfdgz94l2b3ga3qdp7szc";
      };
    };
    trie = 
    {
      pname = "trie";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/trie/archive/1.0.0.tar.gz";
        sha256 = "1slq4kiwnc723dsaw15ms7xxpqz061v8zck1m6iyc5j2li70by62";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/trie/trie.1.0.0";
        hash = "sha256:1ds07ikjjymacnlxfx1widfi7qz0js61lsqqq0xa90501p17nq10";
      };
    };
    tyxml = 
    {
      pname = "tyxml";
      version = "4.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.6.0/tyxml-4.6.0.tbz";
        sha256 = "1p82r68lxk6wzxihzd620a6kzp27vn548j2cr970l4jfdcy6gsxz";
      };
      opamInputs = 
      {
        inherit (selection) uutf seq re ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml/tyxml.4.6.0";
        hash = "sha256:02pnpfr487d077arnvras1a6p52san6l5xkw0adgaxqpi7cf1cqy";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    uri = 
    {
      pname = "uri";
      version = "4.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
        sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
      };
      opamInputs = 
      {
        inherit (selection) stringext ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri/uri.4.4.0";
        hash = "sha256:1jzwbdw5lp3bv1hw9kdi86d0yzzfg5shp0571kw9gkhypisr7jva";
      };
    };
    uri-sexp = 
    {
      pname = "uri-sexp";
      version = "4.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
        sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri-sexp/uri-sexp.4.4.0";
        hash = "sha256:0vv34q5lxr1s0j282j3sgvkhspyn37rwa5n48y790w5a8p39ik21";
      };
    };
    utop = 
    {
      pname = "utop";
      version = "2.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/utop/releases/download/2.14.0/utop-2.14.0.tbz";
        sha256 = "1a9v4w6nw8dp30qk1bkk6vhpp6vgs46gx8b32jkj91a5bfyakm8g";
      };
      opamInputs = 
      {
        inherit (selection) zed xdg react ocamlfind ocaml lwt_react lwt logs
        lambda-term dune cppo base-unix base-threads;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/utop/utop.2.14.0";
        hash = "sha256:1x2f0nl0rah8cixal8lm2fckl4416pbpllv45fv4f1l6abz6immr";
      };
    };
    uucp = 
    {
      pname = "uucp";
      version = "15.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uucp/releases/uucp-15.0.0.tbz";
        sha256 = "0c2k9gkg442l7hnc8rn1vqzn6qh68w9fx7h3nj03n2x90ps98ixc";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        uunf = selection.uunf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uucp/uucp.15.0.0";
        hash = "sha256:0bgf8rrsvnzq9wzlf0grgbz00mhjy5ls6g2az0m41mflxcnaz51j";
      };
    };
    uuseg = 
    {
      pname = "uuseg";
      version = "15.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uuseg/releases/uuseg-15.0.0.tbz";
        sha256 = "1qz130wlmnvb6j7kpvgjlqmdm2jqid4wb1dmrsls4hdm4rp7gk5b";
      };
      opamInputs = 
      {
        inherit (selection) uucp topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuseg/uuseg.15.0.0";
        hash = "sha256:10xmzkzn4dr3mz4xckpsds3klvkfpzfcmg82by5qnhzx8lnwk152";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    vdoml = 
    {
      pname = "vdoml";
      version = "development";
      src = self.directSrc "vdoml";
      opamInputs = 
      {
        inherit (selection) odoc ocamlfind ocaml lwt_ppx lwt logs
        js_of_ocaml-ppx js_of_ocaml-lwt js_of_ocaml dune conf-python-2-7;
      };
      opamSrc = "vdoml.opam";
    };
    x509 = 
    {
      pname = "x509";
      version = "0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-x509/releases/download/v0.14.0/x509-v0.14.0.tbz";
        sha256 = "167lp6rwk44g51n1i74lhzh4i364crjhjbv6xs9j26r6f50z6hlv";
      };
      opamInputs = 
      {
        inherit (selection) rresult ptime pbkdf ocaml mirage-crypto-rng
        mirage-crypto-pk mirage-crypto-ec mirage-crypto logs gmap fmt dune
        domain-name cstruct base64 asn1-combinators;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/x509/x509.0.14.0";
        hash = "sha256:1b75i4cpr639npmamj1zgymvfg2mffkf1d81p7aplqmrddb67ax3";
      };
    };
    xdg = 
    {
      pname = "xdg";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xdg/xdg.3.14.2";
        hash = "sha256:1qmqx47kba7cy4qgwv05n2khz8vn62ljpzm4pnznzwfwblgf8f24";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.1.2/yojson-2.1.2.tbz";
        sha256 = "1ydlvw0f50vg8ia9529ldq07d2jyqzjr9230pyywr9y8pymz3wjr";
      };
      opamInputs = 
      {
        inherit (selection) seq ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.1.2";
        hash = "sha256:10cqyg4ykrfc39lfb0xhykknym1pz5saivq3ighgns4a1rnkixf3";
      };
    };
    zarith = 
    {
      pname = "zarith";
      version = "1.13";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/Zarith/archive/release-1.13.tar.gz";
        sha256 = "0fzqnc4h9nisszykz2fyfrwvfpq7iqymi4kgwvb3l450zqrnv0m5";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zarith/zarith.1.13";
        hash = "sha256:0k6zyd28qa6rgs3z8k1z3b8wspi5w570lkfph6z894y5n289aih4";
      };
    };
    zed = 
    {
      pname = "zed";
      version = "3.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/zed/archive/refs/tags/3.2.3.tar.gz";
        sha256 = "13057gf7z2zl4wps8mzf84pm7y52p5z0vzv9zrlp4cl2ss2k0sjb";
      };
      opamInputs = 
      {
        inherit (selection) uutf uuseg uucp uchar result react ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zed/zed.3.2.3";
        hash = "sha256:11pgssqmpr49z1ibnl2hakkdaznhna7nc2zzyhd04x94wnmmk9cm";
      };
    };
  };
}

