#!bash -eu
here="$(dirname "$0")"
. "$here/env.sh"
ocamlbuild_args="-quiet"
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
	ocamlbuild_args=""
fi
# ocamlbuild_args="-verbose 1"
BUILDDIR="$PWD/$compile_mode"
target="${2#*/}"

pushd "$here/../../src/common/" > /dev/null
gup -u prebuild.targets
gup -u $(cat prebuild.targets)
popd > /dev/null

pushd "../src/$compile_mode" >/dev/null
if [ -e prebuild.targets ]; then
	gup -u prebuild.targets
	gup -u $(cat prebuild.targets)
else
	gup --ifcreate prebuild.targets
fi
gup --always

FLAGS=""
if [ "$build_type" = dev ]; then
	FLAGS="$FLAGS -cflag -w -cflag @a-4-48-44-45-6-58-34"
fi

if [ "$compile_mode" = 'mirage-xen' ]; then
	FLAGS="$FLAGS -lflags -g,-linkpkg,-dontlink,unix"
elif [ "$build_type" = dev ]; then
	FLAGS="$FLAGS -lflags -g"
fi

# for debugging
# ocamlbuild $ocamlbuild_args -use-ocamlfind -show-tags "$target"

set -x

ocamlbuild $ocamlbuild_args \
	-build-dir "$BUILDDIR" -use-ocamlfind $FLAGS "$target"
popd >/dev/null

touch "$2"
gup --contents "$2"
