#!bash -eu
here="$(dirname "$0")"
. "$here/env.sh"
ocamlbuild_args="-quiet"
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
	ocamlbuild_args=""
fi
# ocamlbuild_args="-verbose 1"
BUILDDIR="$PWD/$compile_mode"
target="${2#*/}"

pushd "$here/../../src/common/" > /dev/null
gup -u $(cat prebuild.targets)
popd > /dev/null

pushd "../src/$compile_mode" >/dev/null
gup -u $(cat prebuild.targets)
gup --always
ocamlbuild $ocamlbuild_args \
	-cflag -warn-error -cflag +a-3 \
	-build-dir "$BUILDDIR" -use-ocamlfind "$target"
popd >/dev/null

touch "$2"
gup --contents "$2"
