#!bash -eu

builddir="$(dirname "$2")"
obj="$builddir/main.native.o"

if pkg-config --print-errors --exists mirage-xen 2>/dev/null; then
	echo "Using global PKGCONFIG"
else
	export PKG_CONFIG_PATH="$(opam config var prefix)/lib/pkgconfig"
fi

gup -u "$obj"

# extracted from `mirage configure` makefile
pkg-config --print-errors --exists mirage-xen
LIB_DIRS="$(ocamlfind query tcpip.xen io-page.xen nocrypto sha zarith-xen zarith safepass)"
[ -n "$LIB_DIRS" ]
OCAML_ROOT="$(ocamlc -where)"
[ -n "$OCAML_ROOT" ]

LD_FLAGS="$(echo -e "$LIB_DIRS\n$OCAML_ROOT" | sed -e 's/^/-L /')"

set -x
ld -d -static -nostdlib \
	"$obj" \
	-L /usr/lib/debug/usr/lib64 \
	$LD_FLAGS \
	-ltcpip_xen_stubs \
	-lio_page_xen_stubs \
	-lnocrypto_stubs \
	-lsha256 \
	-lzarith-xen \
	-lsafepass_stubs \
	-lnums \
	-L "$builddir/src" \
	$(pkg-config --static --libs mirage-xen gmp-xen) \
	$(gcc -print-libgcc-file-name) \
	-o "$1"

