#!bash -eu
gup --always
cd "$(dirname "$2")"
basename="$(basename "$2" .mlpack)"
dir="$(echo "$basename" | sed -e 's/^passe_//')"

find -H "$dir" -maxdepth 1 -type f -name '*.ml*' | sed -e 's/\.ml.*//' | sort -u > "$1"
exclude="$basename.exclude"
if [ -e "$exclude" ]; then
	contents="$(cat "$1" | grep -E -v "$(grep -v '^#' "$exclude")")"
	echo "$contents" > "$1"
else
	gup --ifcreate "$exclude"
fi

gup --contents "$1"
