#!bash -eu
here="$(dirname "$0")"
. "$here/env.sh"
ocamlbuild_args="-quiet"
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
	ocamlbuild_args=""
fi
# ocamlbuild_args="-verbose 1"
BUILDDIR="$PWD/$compile_mode"
target="${2#*/}"

pushd "$here/../../src/common/" > /dev/null
gup -u $(cat prebuild.targets)
popd > /dev/null

pushd "../src/$compile_mode" >/dev/null
if [ -e prebuild.targets ]; then
	gup -u prebuild.targets
	gup -u $(cat prebuild.targets)
else
	gup --ifcreate prebuild.targets
fi
gup --always

FLAGS=""
if [ "$compile_mode" = 'mirage-xen' ]; then
	FLAGS="$FLAGS -lflags -g,-linkpkg,-dontlink,unix"
fi

rainbow="$(which rainbow 2>/dev/null || true)"
if [ -z "$rainbow" ]; then
	rainbow="ocamlbuild"
else
	rainbow="$rainbow -- ocamlbuild"
fi

# for debugging
# ocamlbuild $ocamlbuild_args -use-ocamlfind -show-tags "$target"

set -x

$rainbow $ocamlbuild_args \
	-cflag -warn-error -cflag +a-3 \
	-build-dir "$BUILDDIR" -use-ocamlfind $FLAGS "$target"
popd >/dev/null

touch "$2"
gup --contents "$2"
