#!bash -eu
. "$(dirname "$0")"/env.sh
base="${2%.*}"
src="$base.byte"
gup -u "$src"

# required for `react`:
common_args="+js_of_ocaml/weak.js -disable genprim"

if [ "$build_type" = "prod" ]; then
	js_of_ocaml -opt 3 $common_args -o "$1" "$src"
else
	js_of_ocaml $common_args -debuginfo -o "$1" "$src"
fi
