#!/bin/bash
set -eu
t="_build/native/test/main.byte"
gup -u "$t"
# we poke the server on test boundaries,
# which requires the sequential runner
# to make sure tests don't overlap
exec "$t" -runner sequential "$@"
