#!/bin/bash
set -eu
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
fi
t="_build/default/src/test/main.exe"
dune build "$t"
# we poke the server on test boundaries,
# which requires the sequential runner
# to make sure tests don't overlap
exec "$t" -runner sequential "$@"
