#!/bin/bash
set -eu
if [ "${GUP_XTRACE:-}" = 1 ]; then
	set -x
fi
t="_build/native/test/main.byte"
gup -u -j4 "$t"
# we poke the server on test boundaries,
# which requires the sequential runner
# to make sure tests don't overlap
exec "$t" -runner sequential "$@"
